// src/components/Markdown.tsx
import { Fragment, FunctionComponent } from "react"
import TeX from "./TeX"
import { Link } from "react-router-dom"
import { parseMarkdown, ParseTree, ParseTreeNode } from "../utils/parseMarkdown"
import SyntaxHighlighter from "react-syntax-highlighter"
import {
  solarizedLight,
  solarizedDark,
} from "react-syntax-highlighter/dist/esm/styles/hljs"
import { useTheme } from "../hooks/useTheme"

/**
 * Function to render a given markdown-like string as a React component
 *
 * @param props
 * @param props.md The markdown-like string to render
 * @returns The React component
 */
export const Markdown: FunctionComponent<{ md: string }> = ({ md }) => {
  return <MarkdownTree parseTree={parseMarkdown(md)} />
}

/**
 * Function to render a given parseTree as a React component
 *
 * @param props
 * @param props.parseTree The parse tree to render
 * @returns The React component
 */
export const MarkdownTree: FunctionComponent<{
  parseTree: ParseTree
}> = ({ parseTree }) => {
  // TODO: Implement this function
  return (
    <>
      {parseTree.map((node, index) => (
        <Fragment key={index}>
          <MarkdownTreeNode parseTreeNode={node} />
        </Fragment>
      ))}
    </>
  )
}

/**
 * Function to render a given parseTreeNode as a React component
 *
 * @param props
 * @param props.parseTreeNode The parse tree node to render
 * @returns The React component
 */
export const MarkdownTreeNode: FunctionComponent<{
  parseTreeNode: ParseTreeNode
}> = ({ parseTreeNode }) => {
  const { theme } = useTheme()
  if (typeof parseTreeNode === "string") {
    return <>{parseTreeNode}</>
  }
  if (parseTreeNode.kind === "$$") {
    return <TeX tex={parseTreeNode.child} block />
  }
  if (parseTreeNode.kind === "$") {
    return <TeX tex={parseTreeNode.child} />
  }
  if (parseTreeNode.kind === "**") {
    return (
      <b>
        <MarkdownTree parseTree={parseTreeNode.child} />
      </b>
    )
  }
  if (parseTreeNode.kind === "*") {
    return (
      <i>
        <MarkdownTree parseTree={parseTreeNode.child} />
      </i>
    )
  }
  if (parseTreeNode.kind === "`") {
    return <span className="font-mono">{parseTreeNode.child}</span>
  }
  if (parseTreeNode.kind === "```") {
    return (
      <div className="my-5">
        <SyntaxHighlighter
          language={parseTreeNode.language}
          style={theme === "light" ? solarizedLight : solarizedDark}
        >
          {parseTreeNode.child}
        </SyntaxHighlighter>
      </div>
    )
  }
  if (parseTreeNode.kind === "a") {
    return (
      <Link to={parseTreeNode.url}>
        <MarkdownTree parseTree={parseTreeNode.child} />
      </Link>
    )
  }
  if (parseTreeNode.kind === ">") {
    return (
      <blockquote className="my-4 border-l-4 pl-2">
        <MarkdownTree parseTree={parseTreeNode.child} />
      </blockquote>
    )
  }

  // will never be reached:
  return <></>
}

// svelte-front-end/src/lib/components/markdown.svelte
<script lang="ts">
  import type { Snippet } from "svelte"
  import { parseMarkdown, type ParseTree, type ParseTreeNode } from "@shared/utils/parseMarkdown"

  interface Props {
    md: string
    children?: Snippet
  }

  const { md, children }: Props = $props()
  const t = $derived(parseMarkdown(md))
</script>

{#snippet tree(t: ParseTree)}
  {#each t as n}
    {@render node(n)}
  {/each}
{/snippet}

{#snippet node(x: ParseTreeNode)}
  {#if typeof x === "string"}
    {x}
  {:else if x.kind === "`"}
    <span class="rounded-sm bg-gray-200 px-2 py-1 font-mono dark:bg-gray-700">{x}</span>
  {:else if x.kind === "```"}
    <!-- TODO -->
    <pre class="block">{x}</pre>
  {:else if x.kind === "$$" || x.kind === "$"}
    <!-- TODO -->
    {x.kind}{x}{x.kind}
  {:else if x.kind === "**"}
    <strong>{@render tree(x.child)}</strong>
  {:else if x.kind === "*"}
    <em>{@render tree(x.child)}</em>
  {:else if x.kind === ">"}
    <blockquote class="my-4 border-l-4 pl-2">{@render tree(x.child)}</blockquote>
  {:else if x.kind === "a"}
    <a href={x.url}>{@render tree(x.child)}</a>
  {:else if x.kind === "list"}
    <ul>
      {#each x.child as c}
        <li>{@render tree(c)}</li>
      {/each}
    </ul>
  {:else}
    TODO: Rendering of Markdown nodes <pre>{x.kind}</pre>
    is not yet implemented.
  {/if}
{/snippet}

{@render tree(t)}
{@render children?.()}
