// packages/svelte-front-end/src/lib/components/ViewSingleQuestion.svelte
<script lang="ts">
  import Loading from "$lib/components/Loading.svelte"
  import QuestionComponent from "$lib/components/QuestionComponent.svelte"
  import type { Result } from "$lib/components/types.ts"
  import type { Language } from "@shared/api/Language.ts"
  import type { Parameters } from "@shared/api/Parameters"
  import type { QuestionGenerator } from "@shared/api/QuestionGenerator.ts"
  import { createQuery } from "@tanstack/svelte-query"

  interface Props {
    generator: QuestionGenerator
    parameters: Parameters
    seed: string
    onResult: ((result: Result) => void) | undefined
    lang: Language
  }
  const { generator, parameters, seed, onResult, lang }: Props = $props()

  const queryKey = [generator, lang, parameters, seed]
  const questionQuery = createQuery({
    queryKey,
    queryFn: async () => generator.generate(lang, parameters, seed),
  })
</script>

{#if $questionQuery.isError}
  {$questionQuery.error}
{:else if $questionQuery.isLoading || !$questionQuery.isSuccess}
  <Loading {lang} />
{:else}
  <!-- Todo: Missing useFormat() -->
  <QuestionComponent question={$questionQuery.data.question} {onResult} />
{/if}

// front-end/src/routes/ViewSingleQuestion.tsx
import { useNavigate } from "react-router-dom"
import { validateParameters, type Parameters } from "@shared/api/Parameters"
import { questionToJSON, type QuestionGenerator } from "@shared/api/QuestionGenerator"
import { serializeGeneratorCall } from "@shared/api/QuestionRouter"
import { questionToTex } from "@shared/utils/toLatex"
import { useQuery } from "@tanstack/react-query"
import { HorizontallyCenteredDiv } from "../components/CenteredDivs"
import Loading from "../components/Loading"
import { QuestionComponent, type Result } from "../components/QuestionComponent"
import { useFormat } from "../hooks/useDebug"
import { useTranslation } from "../hooks/useTranslation"
import { Debug } from "./debug"

export function ViewSingleQuestion({
  generator,
  parameters,
  seed,
  onResult,
}: {
  generator: QuestionGenerator
  parameters: Parameters
  seed: string
  onResult?: (result: Result) => void
}) {
  const { lang } = useTranslation()
  const navigate = useNavigate()
  const { debug, format } = useFormat()

  const queryKey = [generator, lang, parameters, seed]
  const questionQuery = useQuery({
    queryKey,
    queryFn: async () => generator.generate(lang, parameters, seed),
  })

  if (questionQuery.isError) throw questionQuery.error

  if (!validateParameters(parameters, generator.expectedParameters)) {
    throw new Error("Invalid parameters: " + JSON.stringify(parameters))
  }
  return questionQuery.isLoading || !questionQuery.isSuccess ? (
    <Loading />
  ) : format == "react" ? (
    <>
      <QuestionComponent
        key={serializeGeneratorCall({
          generator,
          parameters,
          seed,
        })}
        question={questionQuery.data.question}
        onResult={onResult ?? (() => navigate("/"))}
      />
      {debug && <Debug />}
    </>
  ) : (
    <>
      <HorizontallyCenteredDiv className="mt-10 w-full flex-grow overflow-y-scroll">
        <h1>{questionQuery.data.question.name}</h1>
        <div className={`container mx-auto p-4`}>
          <pre className="overflow-auto rounded-md bg-gray-800 p-4 text-white">
            <code>
              {(format == "latex" ? questionToTex : questionToJSON)(questionQuery.data.question)}
            </code>
          </pre>
        </div>
      </HorizontallyCenteredDiv>
      <Debug />
    </>
  )
}
