// src/components/SortableItem.tsx
import type {
  DraggableSyntheticListeners,
  UniqueIdentifier,
} from "@dnd-kit/core"
import { useSortable } from "@dnd-kit/sortable"
import { CSS } from "@dnd-kit/utilities"
import { createContext, PropsWithChildren, useContext, useMemo } from "react"
import { RxDragHandleHorizontal } from "react-icons/rx"

interface Props {
  id: UniqueIdentifier
  disabled?: boolean
}

interface Context {
  attributes: Record<string, any>
  listeners: DraggableSyntheticListeners
  ref(node: HTMLElement | null): void
}

const SortableItemContext = createContext<Context>({
  attributes: {},
  listeners: undefined,
  ref() {},
})

export function SortableItem({
  children,
  id,
  disabled = false,
}: PropsWithChildren<Props>) {
  const {
    attributes,
    isDragging,
    listeners,
    setNodeRef,
    setActivatorNodeRef,
    transform,
    transition,
  } = useSortable({
    id,
  })
  const context = useMemo(
    () => ({
      attributes,
      listeners,
      ref: setActivatorNodeRef,
    }),
    [attributes, listeners, setActivatorNodeRef]
  )
  return (
    <SortableItemContext.Provider value={context}>
      <li
        className={`flex flex-grow select-none list-none items-center justify-between gap-5 ${
          disabled ? "cursor-default" : ""
        }  ${isDragging ? "z-10" : ""}`}
        ref={disabled ? null : setNodeRef}
        style={{ transform: CSS.Translate.toString(transform), transition }}
        {...attributes}
        {...listeners}
      >
        {children}
      </li>
    </SortableItemContext.Provider>
  )
}

export function DragHandle() {
  const { attributes, listeners, ...rest } = useContext(SortableItemContext)
  const ref = (x: HTMLElement | null) => rest.ref(x)
  return (
    <button
      className="px-2 py-5 hover:bg-black/20"
      {...attributes}
      {...listeners}
      ref={ref}
    >
      <RxDragHandleHorizontal />
    </button>
  )
}

// packages/svelte-front-end/src/lib/components/DnD/SortableItem.svelte
<script lang="ts">
  import Markdown from "$lib/components/markdown/markdown.svelte"
  import { GripVertical } from "lucide-svelte"
  import type { UniqueIdentifier } from "@dnd-kit-svelte/core"
  import { useSortable } from "@dnd-kit-svelte/sortable"
  import { CSS, styleObjectToString } from "@dnd-kit-svelte/utilities"

  interface Item {
    id: UniqueIdentifier
    content: string
  }

  let { task, disabled }: { task: Item; disabled?: boolean } = $props()

  const { attributes, listeners, node, transform, transition, isDragging, isSorting } = useSortable({
    id: task.id,
  })

  const style = $derived(
    styleObjectToString({
      transform: CSS.Transform.toString(transform.current),
      transition: isSorting.current ? transition.current : undefined,
      zIndex: isDragging.current ? 1 : undefined,
    }),
  )
</script>

<div
  class="relative select-none"
  bind:this={node.current}
  {style}
  {...!disabled ? listeners.current : {}}
  {...attributes.current}
>
  <!-- Original element - becomes invisible during drag but maintains dimensions -->
  <div
    class={[
      `flex w-auto items-center rounded-md bg-gray-200 p-4 hover:bg-gray-300 dark:bg-gray-700 hover:dark:bg-gray-600`,
      { invisible: isDragging.current },
    ]}
  >
    <GripVertical class={`mr-4 ${disabled ? "" : "hover:cursor-pointer"}`} />
    <Markdown md={task.content} />
  </div>
</div>
