// packages/svelte-front-end/src/lib/components/ExerciseTextInput.svelte
<script lang="ts">
  import InteractWithQuestion from "$lib/components/InteractWithQuestion.svelte"
  import Markdown from "$lib/components/markdown/markdown.svelte"
  import type { MODE, Result } from "$lib/components/types.ts"
  import { Button } from "$lib/components/ui/button"
  import { inputClass } from "$lib/components/ui/input/cnInput.ts"
  import { playSound } from "$lib/sound.svelte.ts"
  import { globalTranslations } from "$lib/translation.ts"
  import { isMobileOrTablet } from "$lib/utils/deviceInformation.ts"
  import { onMount } from "svelte"
  import type { Language } from "@shared/api/Language.ts"
  import type { FreeTextFeedback, FreeTextQuestion } from "@shared/api/QuestionGenerator.ts"
  import { tFunction } from "@shared/utils/translations.ts"

  interface Props {
    question: FreeTextQuestion
    permalink?: string
    onResult?: (result: Result) => void
    regenerate?: () => void
    lang: Language
  }
  const { question, permalink, onResult, regenerate, lang }: Props = $props()
  const { t } = $derived(tFunction([globalTranslations], lang))

  let questionState: {
    mode: MODE
    text: string
    feedbackObject?: FreeTextFeedback
    formatFeedback?: string
  } = $state({
    mode: "invalid",
    text: "",
  })

  let userInputRef: HTMLInputElement | null = $state(null)
  onMount(() => {
    if (!isMobileOrTablet) {
      userInputRef!.focus({ preventScroll: true })
    }
  })

  function handleChange(event: Event) {
    setText((event.target as HTMLInputElement).value)
  }

  function setText(text: string) {
    questionState = {
      ...questionState,
      text,
    }
    if (question.checkFormat) {
      void Promise.resolve(question.checkFormat({ text })).then(({ valid, message }) => {
        questionState = {
          ...questionState,
          mode: valid ? "draft" : "invalid",
          formatFeedback: message,
        }
      })
    } else {
      questionState = {
        ...questionState,
        mode: text.trim().length > 0 ? "draft" : "invalid",
      }
    }
  }

  function insertText(text: string): void {
    if (userInputRef === null) {
      setText(text)
      return
    }

    setText(
      userInputRef.value.slice(0, userInputRef.selectionStart ?? 0) +
        text +
        userInputRef.value.slice(userInputRef.selectionEnd ?? 0),
    )

    userInputRef.focus()
  }

  function handleClick() {
    if (questionState.mode === "draft") {
      if (question.feedback !== undefined) {
        questionState.mode = "submitted"
        void Promise.resolve(question.feedback({ text: questionState.text })).then((feedbackObject) => {
          let mode: MODE = "draft"
          if (feedbackObject.correct === true) {
            playSound("pass")
            mode = "correct"
          } else if (feedbackObject.correct === false) {
            playSound("fail")
            mode = "incorrect"
          }
          questionState.mode = mode
          questionState.feedbackObject = feedbackObject
        })
      }
    } else if (questionState.mode === "correct" || questionState.mode === "incorrect") {
      if (onResult) onResult(questionState.mode)
    }
  }

  function onKeyDown(e: Event) {
    if (!(e instanceof KeyboardEvent)) {
      return
    }
    const key = e.key
    if (key === "Enter") {
      e.preventDefault()
      handleClick()
    }
  }

  const msgColor = $derived(
    questionState.mode === "draft"
      ? "text-green-600 dark:text-green-400"
      : "text-red-600 dark:text-red-400",
  )
</script>

<InteractWithQuestion
  {permalink}
  name={question.name}
  {regenerate}
  footerMode={questionState.mode}
  footerMessage={messageList}
  {lang}
  handleFooterClick={handleClick}
>
  <Markdown md={question.text ?? ""} />
  <br />
  <br />
  <div class="flex place-items-center gap-2 pl-3">
    <Markdown md={question.prompt ?? ""} />
    <input
      class="${inputClass}"
      bind:this={userInputRef}
      disabled={questionState.mode === "correct" || questionState.mode === "incorrect"}
      value={questionState.text}
      oninput={handleChange}
      type="text"
      placeholder={question.placeholder}
    />
    <div class={`flex h-12 items-center ${msgColor}`}>
      <div>
        <Markdown md={questionState.formatFeedback ?? ""} />
      </div>
    </div>
  </div>
  <div class="py-5 text-slate-600 dark:text-slate-400">
    <Markdown md={question.bottomText ?? ""} />
  </div>
  <div class="flex flex-wrap gap-2">
    {#each question.typingAid ?? [] as el}
      <Button
        variant="secondary"
        onclick={() => insertText(el.input)}
        aria-label={t("typing-aid.label", [el.label])}
      >
        <Markdown md={el.text ?? ""} />
      </Button>
    {/each}
  </div>
</InteractWithQuestion>

{#snippet messageList()}
  <div class="flex-col">
    {#if questionState.mode === "correct"}
      {@render correct()}
    {:else if questionState.mode === "incorrect"}
      {#if questionState.feedbackObject?.feedbackText}
        {@render feedbackText()}
      {/if}
      {#if questionState.feedbackObject?.correctAnswer}
        {@render correctAnswer()}
      {/if}
    {:else}
      {@render incorrect()}
    {/if}
  </div>
{/snippet}

{#snippet correct()}
  <b class="text-2xl">{t("feedback.correct")}</b>
{/snippet}

{#snippet incorrect()}
  <b class="text-2xl">{t("incorrect")}</b>
{/snippet}

{#snippet feedbackText()}
  <Markdown md={questionState.feedbackObject?.feedbackText ?? ""} />
  <br />
{/snippet}

{#snippet correctAnswer()}
  <b class="text-xl">{t("feedback.possible-correct-solution")}:</b>
  <br />
  <Markdown md={questionState.feedbackObject?.correctAnswer ?? ""} />
{/snippet}

<svelte:window on:keydown={onKeyDown} />

// src/components/ExerciseTextInput.tsx
import { ReactNode, useState } from "react"
import { useTranslation } from "react-i18next"
import useGlobalDOMEvents from "../hooks/useGlobalDOMEvents"
import { useSound } from "../hooks/useSound"
import { Question } from "./Question"

export function ExerciseTextInput({
  title,
  children,
  prompt,
  feedback,
  bottomNote,
  regenerate,
  onResult = () => {},
  permalink,
  viewOnly = false,
  possibleCorrectSolution,
}: {
  title: string
  children?: ReactNode
  prompt?: ReactNode
  feedback: (text: string) => {
    isValid: boolean
    isCorrect: boolean
    FeedbackText: ReactNode
  }
  bottomNote?: ReactNode
  regenerate?: () => void
  onResult?: (result: "correct" | "incorrect" | "abort") => void
  allowMultiple?: boolean
  permalink?: string
  viewOnly?: boolean
  possibleCorrectSolution?: ReactNode
}) {
  const { t } = useTranslation()
  const { playSound } = useSound()
  const [text, setText] = useState("")
  const [savedMode, setMode] = useState(
    "disabled" as "disabled" | "verify" | "correct" | "incorrect"
  )

  const { isValid, isCorrect, FeedbackText } = feedback(text)
  const msgColor = isValid
    ? "text-green-600 dark:text-green-400"
    : "text-red-600 dark:text-red-400"
  const mode = !isValid
    ? "disabled"
    : savedMode === "disabled"
    ? "verify"
    : savedMode
  const message =
    mode === "correct" ? (
      <b className="text-2xl">{t("feedback.correct")}</b>
    ) : mode === "incorrect" ? (
      possibleCorrectSolution ? (
        <>
          <b className="text-xl">{t("feedback.possible-correct-solution")}:</b>
          <br />
          {possibleCorrectSolution}
        </>
      ) : (
        <b className="text-2xl">{t("feedback.incorrect")}</b>
      )
    ) : null
  function handleClick() {
    if (mode === "disabled") {
      if (!viewOnly) setMode("verify")
    } else if (mode === "verify") {
      if (FeedbackText === null || !isValid) return
      if (isCorrect) {
        playSound("pass")
        setMode("correct")
      } else {
        playSound("fail")
        setMode("incorrect")
      }
    } else if (mode === "correct" || mode === "incorrect") {
      onResult(mode)
    }
  }
  useGlobalDOMEvents({
    keydown(e: Event) {
      const key = (e as KeyboardEvent).key
      if (key === "Enter") {
        e.preventDefault()
        handleClick()
      }
    },
  })
  return (
    <Question
      permalink={permalink}
      title={title}
      regenerate={regenerate}
      footerMode={mode}
      footerMessage={message}
      handleFooterClick={handleClick}
    >
      {children}
      <br />
      <br />
      <div className="flex place-items-center gap-2 pl-3">
        {prompt}
        <input
          autoFocus
          type="text"
          onChange={(e) => {
            setText(e.target.value)
          }}
          value={text}
          className="rounded-md bg-gray-300 p-2 dark:bg-gray-900"
          disabled={mode === "correct" || mode === "incorrect"}
        />
        <div className={`flex h-12 items-center ${msgColor}`}>
          <div>{FeedbackText}</div>
        </div>
      </div>
      <div className="py-5 text-slate-600 dark:text-slate-400">
        {bottomNote}
      </div>
    </Question>
  )
}
