// packages/svelte-front-end/src/lib/components/QuestionHeader.svelte
<script lang="ts">
  import { browser } from "$app/environment"
  import MyTooltip from "$lib/components/ui/MyTooltip.svelte"
  import { prefixURL } from "$lib/config.js"
  import { globalTranslations } from "$lib/translation.ts"
  import { getLanguage } from "$lib/utils/langState.svelte.ts"
  import { Tooltip } from "bits-ui"
  import { Link, RefreshCwIcon } from "lucide-svelte"
  import type { Language } from "@shared/api/Language.ts"
  import { tFunction } from "@shared/utils/translations.ts"

  interface Props {
    title?: string
    regenerate?: () => void
    permalink?: string
  }

  const { title, regenerate, permalink }: Props = $props()
  const lang: Language = $derived(getLanguage())
  const { t } = $derived(tFunction([globalTranslations], lang))
  let recentlyCopied: boolean = $state(false)

  function handleClick() {
    if (!browser) return
    void navigator.clipboard.writeText(prefixURL + "/" + permalink).then(() => {
      recentlyCopied = true
    })
  }

  function mouseLeave() {
    recentlyCopied = false
  }
</script>

<h1 class="text-2xl font-semibold">
  {title !== undefined && title + " "}
  {#if permalink}
    <Tooltip.Provider>
      <MyTooltip
        open={recentlyCopied}
        contentProps={{ sideOffset: 5 }}
        triggerProps={{ onclick: handleClick, onmouseleave: mouseLeave }}
      >
        {#snippet trigger()}
          <Link class="pl-1" />
        {/snippet}
        {(recentlyCopied ? t("copyLinkCopied") : t("copyLinkTooltip")) || ""}
      </MyTooltip>
    </Tooltip.Provider>
  {/if}
  {#if regenerate}
    <Tooltip.Provider>
      <MyTooltip contentProps={{ sideOffset: 5 }} triggerProps={{ onclick: regenerate }}>
        {#snippet trigger()}
          <RefreshCwIcon class="pl-1" size={20} strokeWidth={1.5} absoluteStrokeWidth />
        {/snippet}
        {t("generate-new-exercise-of-same-type")}
      </MyTooltip>
    </Tooltip.Provider>
  {/if}
</h1>

// src/components/QuestionHeader.tsx
import { useState } from "react"
import { useTranslation } from "react-i18next"
import { BiLink, BiRefresh } from "react-icons/bi"
import { prefixURL } from "../config"
import { Tooltip } from "react-tooltip"
import "react-tooltip/dist/react-tooltip.css"

export function QuestionHeader({
  title,
  regenerate,
  permalink,
}: {
  title?: string
  regenerate?: () => void
  permalink?: string
}) {
  const { t } = useTranslation()
  const idString = permalink ? permalink.replaceAll("/", "-") : ""
  const [recentlyCopied, setRecentlyCopied] = useState(false)
  return (
    <h1 className="my-5">
      {title != undefined && title + " "}
      {permalink && (
        <>
          <button
            type="button"
            id={`copy-link-${idString}`}
            onClick={() => {
              void navigator.clipboard
                .writeText(prefixURL + "/" + permalink)
                .then(() => setRecentlyCopied(true))
            }}
            onMouseLeave={() => {
              setTimeout(() => setRecentlyCopied(false), 200)
            }}
          >
            <BiLink className="inline" />
          </button>
          <Tooltip
            anchorSelect={`#copy-link-${idString}`}
            place="right"
            className="text-sm font-normal"
          >
            {(recentlyCopied ? t("copyLinkCopied") : t("copyLinkTooltip")) ||
              ""}
          </Tooltip>
        </>
      )}
      {regenerate && (
        <>
          <button
            type="button"
            id={`regenerate-${idString}`}
            onClick={regenerate}
          >
            <BiRefresh className="inline" />
          </button>
          <Tooltip
            anchorSelect={`#regenerate-${idString}`}
            place="right"
            className="text-sm font-normal"
          >
            {t("generate-new-exercise-of-same-type")}
          </Tooltip>
        </>
      )}
    </h1>
  )
}
