// packages/svelte-front-end/src/lib/components/DnD/SortableList.svelte
<script lang="ts">
  import Droppable from "$lib/components/DnD/droppable.svelte"
  import { crossfade } from "svelte/transition"
  import { DndContext, DragOverlay, type DragEndEvent, type DragStartEvent } from "@dnd-kit-svelte/core"
  import { arrayMove, SortableContext } from "@dnd-kit-svelte/sortable"
  import SortableItem from "./SortableItem.svelte"
  import { dropAnimation, sensors } from "./utils.ts"

  export interface Item {
    id: string
    position: number
    content: string
  }

  interface Props {
    initItems: Item[]
    onChange: (array: Item[]) => void
    disabled: boolean
  }
  const { initItems, onChange, disabled }: Props = $props()

  const items = $derived<Item[]>(initItems)
  let activeId = $state<string | null>(null)
  const activeItem = $derived(items.find((item) => item.id === activeId))

  function handleDragStart(event: DragStartEvent) {
    activeId = event.active.id as string
  }

  function handleDragEnd({ active, over }: DragEndEvent) {
    if (!over) return

    const overItem = $state.snapshot(items.find((item) => item.id === over?.id))
    if (!overItem || activeId === overItem.id) return

    const oldIndex = items.findIndex((item) => item.id === active.id)
    const newIndex = items.findIndex((item) => item.id === over.id)
    onChange(arrayMove(items, oldIndex, newIndex))

    activeId = null
  }

  const [send, receive] = crossfade({ duration: 100 })
</script>

<DndContext {sensors} onDragStart={handleDragStart} onDragEnd={handleDragEnd}>
  <div class="flex items-center justify-center">
    {@render taskList("in-progress", items)}
  </div>

  <DragOverlay {dropAnimation}>
    {#if activeItem && activeId}
      <SortableItem task={activeItem} />
    {/if}
  </DragOverlay>
</DndContext>

{#snippet taskList(id: string, tasks: Item[])}
  <SortableContext items={tasks}>
    <Droppable class="p-3 pt-6" {id}>
      <div class="grid gap-2">
        {#each tasks as task (task.id)}
          <div class="" in:receive={{ key: task.id }} out:send={{ key: task.id }}>
            <SortableItem {task} {disabled} />
          </div>
        {/each}
      </div>
    </Droppable>
  </SortableContext>
{/snippet}

// src/components/SortableList.tsx
import {
  DndContext,
  KeyboardSensor,
  PointerSensor,
  UniqueIdentifier,
  useSensor,
  useSensors,
} from "@dnd-kit/core"
import {
  arrayMove,
  SortableContext,
  sortableKeyboardCoordinates,
} from "@dnd-kit/sortable"
import { ReactNode } from "react"
import { RxDragHandleHorizontal } from "react-icons/rx"
import { AnswerBox } from "./AnswerBox"

import { DragHandle, SortableItem } from "./SortableItem"

interface BaseItem {
  key: UniqueIdentifier
  element: ReactNode
}

interface Props<T extends BaseItem> {
  items: T[]
  onChange: (array: T[]) => void
  className?: string
  disabled?: boolean
}

export function SortableList<T extends BaseItem>({
  items,
  onChange,
  className = "",
  disabled = false,
  ...props
}: Props<T>) {
  // const [active, setActive] = useState<Active | null>(null)
  // const activeItem = useMemo(
  //   () => items.find((item) => item.key === active?.id),
  //   [active, items]
  // )
  const sensors = useSensors(
    useSensor(PointerSensor),
    useSensor(KeyboardSensor, {
      coordinateGetter: sortableKeyboardCoordinates,
    })
  )

  return (
    <DndContext
      sensors={sensors}
      // onDragStart={({ active }) => {
      //   setActive(active)
      // }}
      onDragEnd={({ active, over }) => {
        if (over && active.id !== over?.id) {
          const activeIndex = items.findIndex(({ key }) => key === active.id)
          const overIndex = items.findIndex(({ key }) => key === over.id)
          onChange(arrayMove(items, activeIndex, overIndex))
        }
        // setActive(null)
      }}
      onDragCancel={() => {
        // setActive(null)
      }}
    >
      {/* <DragOverlay dropAnimation={null}>
      {activeItem ? activeItem.element : null}
      </DragOverlay> */}
      <SortableContext
        items={items.map(({ key }) => ({
          id: key,
        }))}
      >
        <ul
          {...props}
          className={`mx-auto flex max-w-max list-none flex-col gap-2 ${className}`}
          role="application"
        >
          {items.map((item) => (
            <SortableList.Item key={item.key} id={item.key} disabled={disabled}>
              <RxDragHandleHorizontal />
              <AnswerBox TagName="div" disabled={disabled}>
                {item.element}
              </AnswerBox>
              <div></div>
            </SortableList.Item>
          ))}
        </ul>
      </SortableContext>
    </DndContext>
  )
}

SortableList.Item = SortableItem
SortableList.DragHandle = DragHandle
