// packages/svelte-front-end/src/lib/components/Graph/DrawGraph.svelte
<script lang="ts">
  import Edge from "$lib/components/Graph/Edge.svelte"
  import {
    edgeInputSetText,
    nodeInputSetText,
    saveEdgeInput,
    saveNodeInput,
  } from "$lib/components/Graph/inputHelper.ts"
  import Node from "$lib/components/Graph/Node.svelte"
  import { Toggle } from "$lib/components/ui/toggle"
  import { getTheme } from "$lib/theme.svelte.ts"
  import { globalTranslations } from "$lib/translation.ts"
  import { getLanguage } from "$lib/utils/langState.svelte.ts"
  import { getContext } from "svelte"
  import { TextCursorInput } from "@lucide/svelte"
  import { edgeInputFieldID, nodeInputFieldID, type Graph } from "@shared/utils/graph.ts"
  import { tFunction } from "@shared/utils/translations.ts"
  import Markdown from "../markdown/markdown.svelte"
  import { ADD_TEXTFIELDS_AFTERWARDS, type FormContextValue } from "../types.ts"

  type GraphElementStateType = { selected: boolean; group: null | number }

  interface Props {
    maxWidth: number
    maxHeight: number
    graph: Graph
  }
  const { maxWidth, maxHeight, graph }: Props = $props()

  const theme = $derived(getTheme())
  const lang = $derived(getLanguage())
  const { t } = $derived(tFunction([globalTranslations], lang))

  let svgRef: SVGSVGElement | null = null
  const coordinateScale = 60
  const nodeScale = 20
  // limited by the number of colors we have. See tailwind --color-group-0,...,--color-group-7.
  const maxGroups = 8

  const { addTextFieldAfterwards } = getContext<FormContextValue>(ADD_TEXTFIELDS_AFTERWARDS)

  let nodeList = $state(graph.nodes)
  let edgeListFlat = $state(
    graph.edges.flat().filter(graph.directed ? () => true : (e) => e.source < e.target),
  )
  const nodeClickType = $derived(graph.nodeClickType)
  const edgeClickType = $derived(graph.edgeClickType)

  let fieldOpen = $derived(false)
  const nodeId = nodeInputFieldID(graph.inputFieldID)
  const edgeId = edgeInputFieldID(graph.inputFieldID)
  const nodeInputFieldMd = `${nodeId}#TL###`
  const edgeInputFieldMd = `${edgeId}#TL###`

  // register fields first so parent/provider can add them
  if (graph.inputFieldID) {
    if (graph.nodeClickType !== "none") {
      addTextFieldAfterwards(nodeInputFieldMd)
    }
    if (graph.edgeClickType !== "none") {
      addTextFieldAfterwards(edgeInputFieldMd)
    }
  }

  // get context (the provider should keep this object reactive)
  const context = getContext<FormContextValue>(ADD_TEXTFIELDS_AFTERWARDS)

  // derive the live field objects from the context (no one-time copies)
  // this reads the context object each time it changes
  const nodeField = $derived(() => context.textFieldStateValues?.[nodeId])
  const edgeField = $derived(() => context.textFieldStateValues?.[edgeId])

  // derive the text string reactively from nodeField
  const nodeText = $derived(() => nodeField()?.text ?? "")
  const edgeText = $derived(() => edgeField()?.text ?? "")

  $effect(() => {
    saveNodeInput(nodeText(), nodeList, graph, lang)
  })

  $effect(() => {
    saveEdgeInput(edgeText(), edgeListFlat, graph, lang)
  })

  let currentlyDragged = $state<null | number>(null)

  let nodePositions = $derived(
    nodeList.map((u) => {
      return {
        x: u.coords.x * coordinateScale,
        y: u.coords.y * coordinateScale,
      }
    }),
  )
  let nodeStates = $derived<GraphElementStateType[]>(
    nodeList.map((u) => ({
      selected: nodeClickType === "select" || nodeClickType === "selectupgrade" ? !!u.group : false,
      group: nodeClickType === "group" || nodeClickType === "groupupgrade" ? (u.group ?? null) : null,
    })),
  )

  const edgeStates = $derived<GraphElementStateType[]>(
    edgeListFlat.map((e) => ({
      selected: edgeClickType === "select" || edgeClickType === "selectupgrade" ? !!e.group : false,
      group: edgeClickType === "group" || edgeClickType === "selectupgrade" ? (e.group ?? null) : null,
    })),
  )

  function handleSetDragged(i: number) {
    if (currentlyDragged === null) {
      currentlyDragged = i
    }
  }

  function handleClickNode(i: number) {
    if (nodeClickType === "select") {
      if (nodeList[i].group) nodeList[i].group = null
      else nodeList[i].group = 1
    } else if (nodeClickType === "group") {
      const max = Math.min(graph.nodeGroupMax ?? maxGroups, maxGroups) - 1
      nodeList[i].group =
        nodeList[i].group === max ? null : nodeList[i].group === null ? 0 : nodeList[i].group! + 1
    }
    // reassign to trigger reactivity
    nodeList = [...nodeList]

    nodeInputSetText(nodeField(), nodeStates)
  }

  function handleClickEdge(i: number) {
    if (edgeClickType === "select") {
      if (edgeListFlat[i].group) edgeListFlat[i].group = null
      else edgeListFlat[i].group = 1
    } else if (edgeClickType === "group") {
      edgeListFlat[i].group =
        edgeListFlat[i].group === Math.min(graph.edgeGroupMax ?? maxGroups, maxGroups) - 1
          ? null
          : edgeListFlat[i].group === null
            ? 0
            : edgeListFlat[i].group! + 1
    }
    // reassign to trigger reactivity
    edgeListFlat = [...edgeListFlat]

    edgeInputSetText(edgeField(), edgeListFlat, graph)
  }

  const dimensions = graph.getDimensions()
  const margin = 0.7
  const viewBox = {
    x: (dimensions.minX - margin) * coordinateScale,
    y: (dimensions.minY - margin) * coordinateScale,
    width: (dimensions.width + 2 * margin) * coordinateScale,
    height: (dimensions.height + 2 * margin) * coordinateScale,
  }

  const minViewBox = { width: 100, height: 100 }
  if (viewBox.width < minViewBox.width) {
    viewBox.x -= (minViewBox.width - viewBox.width) * 0.5
    viewBox.width = minViewBox.width
  }

  if (viewBox.height < minViewBox.height) {
    viewBox.y -= (minViewBox.height - viewBox.height) * 0.5
    viewBox.height = minViewBox.height
  }

  const viewBoxAspectRatio = Math.min(maxHeight / maxWidth, viewBox.height / viewBox.width)

  function updateDraggedNode(clientX: number, clientY: number) {
    if (currentlyDragged === null || !svgRef) return

    const pt = svgRef.createSVGPoint()
    pt.x = clientX
    pt.y = clientY
    const svgPos = pt.matrixTransform(svgRef.getScreenCTM()?.inverse())

    const nodeRadius = nodeScale
    const minX = viewBox.x - (viewBox.width - maxWidth) / 2
    const maxX = viewBox.x + viewBox.width + (viewBox.width - maxWidth) / 2
    const minY = viewBox.y + nodeRadius
    const maxY = viewBox.y + viewBox.height - nodeRadius

    const constrainedX = Math.max(minX, Math.min(maxX, svgPos.x))
    const constrainedY = Math.max(minY, Math.min(maxY, svgPos.y))

    nodePositions[currentlyDragged].x = constrainedX
    nodePositions[currentlyDragged].y = constrainedY
    nodePositions = [...nodePositions]
  }
</script>

<!-- svelte-ignore a11y_no_static_element_interactions -->
<div class="mb-8">
  <div class="relative">
    <svg
      bind:this={svgRef}
      width={maxWidth}
      height={viewBox.height / viewBox.width > 1 && viewBox.height < maxHeight
        ? viewBox.height * 0.75
        : maxWidth * viewBoxAspectRatio}
      viewBox={`${viewBox.x} ${viewBox.y - 10} ${viewBox.width} ${viewBox.height + 20}`}
      class="bg-secondary mx-auto h-auto max-w-full touch-none overscroll-x-none rounded-2xl"
      onmousemove={(e) => updateDraggedNode(e.clientX, e.clientY)}
      onmouseup={() => {
        if (currentlyDragged !== null) {
          currentlyDragged = null
        }
      }}
      ontouchmove={(e) => {
        // Always prevent default when a node is being dragged
        if (currentlyDragged !== null) {
          e.preventDefault()
          e.stopPropagation()
          updateDraggedNode(e.touches[0].clientX, e.touches[0].clientY)
        }
      }}
      ontouchend={(e) => {
        e.preventDefault()
        e.stopPropagation()
        if (currentlyDragged !== null) {
          currentlyDragged = null
        }
      }}
      ontouchcancel={(e) => {
        e.preventDefault()
        if (currentlyDragged !== null) {
          currentlyDragged = null
        }
      }}
    >
      <g>
        {#each edgeListFlat as e, i (i)}
          <Edge
            u={nodePositions[e.source]}
            v={nodePositions[e.target]}
            weight={e.value}
            directed={graph.directed}
            clickable={edgeClickType === "select" || edgeClickType === "group"}
            state={edgeStates[i]}
            onClickCallback={() => {
              if (edgeClickType === "select" || edgeClickType === "group") {
                handleClickEdge(i)
              }
            }}
          />
        {/each}
      </g>
      <g>
        {#each nodeList as u, i (i)}
          <Node
            pos={nodePositions[i]}
            setDragged={graph.nodeDraggable ? () => handleSetDragged(i) : undefined}
            size={nodeScale}
            label={u.label ?? ""}
            clickable={nodeClickType === "select" || nodeClickType === "group"}
            nodeState={nodeStates[i]}
            onClickCallback={() => {
              if (nodeClickType === "select" || nodeClickType === "group") {
                handleClickNode(i)
              }
            }}
          />
        {/each}
      </g>
    </svg>
    <div
      class="absolute right-28 -bottom-6 flex flex-row items-center space-x-1 rounded-lg dark:border-gray-700 dark:bg-gray-800"
    >
      {#if nodeClickType === "select" || nodeClickType === "group" || edgeClickType === "select" || edgeClickType === "group"}
        <Toggle
          class={`${theme === "dark" ? "text-white" : "text-black"}  hover:cursor-pointer`}
          size="sm"
          variant="bg"
          disabled={nodeField()?.disabled || edgeField()?.disabled}
          onclick={() => {
            fieldOpen = !fieldOpen
          }}
        >
          <TextCursorInput />
        </Toggle>
      {/if}
    </div>
  </div>
  {#if (nodeClickType === "select" || nodeClickType === "group") && fieldOpen}
    <div class="mt-1">
      <div class="mb-1">
        <b>{t("nodeSelection")}</b>
      </div>
      <div class="flex w-full flex-row items-center justify-center space-x-1">
        <div class="mr-0.5 flex-grow">
          <Markdown md={`{{${nodeInputFieldMd}}}`} />
        </div>
      </div>
    </div>
  {/if}
  {#if (edgeClickType === "select" || edgeClickType === "group") && fieldOpen}
    <div class="mt-1">
      <div class="mb-1">
        <b>{t("edgeSelection")}</b>
      </div>
      <div class="flex w-full flex-row items-center justify-center space-x-1">
        <div class="mr-0.5 flex-grow">
          <Markdown md={`{{${edgeInputFieldMd}}}`} />
        </div>
      </div>
    </div>
  {/if}
</div>

// front-end/src/components/DrawGraph.tsx
import { useEffect, useRef, useState, type ReactElement } from "react"
import { RiInputField } from "react-icons/ri"
import type { Language } from "@shared/api/Language.ts"
import { edgeInputFieldID, nodeInputFieldID, type Edge, type Graph } from "@shared/utils/graph"
import {
  checkEdgeInput,
  checkNodeInput,
  parseEdgeText,
  parseNodeText,
  updateGraphEdgeGroup,
  updateGraphEdgeSelected,
  updateGraphNodeGroup,
  updateGraphNodeSelected,
} from "@shared/utils/graphInput.ts"
import { Markdown } from "@/components/Markdown.tsx"
import { Toggle } from "@/components/ui/toggle.tsx"
import { addFormField, useFormField, type TextFieldState } from "@/hooks/useFormContext.ts"
import { useTheme } from "@/hooks/useTheme.ts"
import { useTranslation } from "@/hooks/useTranslation.ts"

export type GraphElementStateType = { selected: boolean; group: null | number }

// limited by the number of colors we have. See tailwind --color-group-0,...,--color-group-7.
const maxGroups = 8

const Node = ({
  pos,
  setDragged,
  size,
  label,
  clickable,
  state,
  onClickCallback,
}: {
  pos: { x: number; y: number }
  setDragged: (() => void) | undefined
  size: number
  label?: string
  clickable: boolean
  state: GraphElementStateType
  onClickCallback: () => void
}) => {
  const nodeStyle = `${state.selected ? "cg-4" : state.group !== null ? `cg-${state.group}` : "primary"} ${clickable ? "cursor-pointer" : "group-hover:fill-accent"}`

  return (
    <g
      className="group"
      transform={`translate(${pos.x},${pos.y})`}
      onMouseDown={setDragged}
      onClick={onClickCallback}
    >
      <circle className={`fill-${nodeStyle} stroke-secondary`} r={size} strokeWidth="6" />
      {label === undefined || label === "" ? null : (
        <text
          textAnchor="middle"
          dominantBaseline="central"
          className={`cursor-${clickable ? "pointer" : "default group-hover:fill-accent-foreground"} ${!state.selected && state.group === null ? "fill-primary-foreground" : ""} select-none`}
          fontSize="1.5em"
        >
          {label}
        </text>
      )}
    </g>
  )
}

const EdgeWeight = ({ weight, x, y }: { weight: number; x: number; y: number }) => {
  return (
    <text
      className="select-none fill-primary"
      textAnchor="middle"
      dominantBaseline="central"
      x={x}
      y={y}
      fontSize="1.5em"
    >
      {weight}
    </text>
  )
}

function getVectorLength(x: number, y: number): number {
  return Math.sqrt(x * x + y * y)
}

function getNormalVec(u: { x: number; y: number }, v: { x: number; y: number }) {
  const orthVec = {
    x: v.y - u.y,
    y: u.x - v.x,
  }
  const orthVecLen = getVectorLength(orthVec.x, orthVec.y)
  return {
    x: orthVec.x / orthVecLen,
    y: orthVec.y / orthVecLen,
  }
}

const Edge = ({
  edgeId,
  u,
  v,
  weight,
  directed,
  clickable,
  state,
  onClickCallback,
}: {
  edgeId: string
  u: { x: number; y: number }
  v: { x: number; y: number }
  weight: number | undefined
  directed: boolean
  clickable: boolean
  state: GraphElementStateType
  onClickCallback: () => void
}) => {
  const edge = []
  const normalVec = getNormalVec(u, v)
  const center = {
    x: (u.x + v.x) / 2,
    y: (u.y + v.y) / 2,
  }

  const edgeStyle = `${state.selected ? "cg-4" : state.group !== null ? `cg-${state.group}` : "primary"}${clickable ? " cursor-pointer" : ""}`

  if (directed) {
    const curveHandle = {
      x: center.x + normalVec.x * 25,
      y: center.y + normalVec.y * 25,
    }
    const arrowDirection = {
      x: v.x - curveHandle.x,
      y: v.y - curveHandle.y,
    }
    const arrowDirectionLength = getVectorLength(arrowDirection.x, arrowDirection.y)

    const arrowDirectionUnit = {
      x: arrowDirection.x / arrowDirectionLength,
      y: arrowDirection.y / arrowDirectionLength,
    }

    edge.push(
      <path
        key={`${edgeId}-l`}
        className={`stroke-${edgeStyle}`}
        strokeWidth="6"
        fill="none"
        d={`M ${u.x} ${u.y} Q ${curveHandle.x} ${curveHandle.y}, ${v.x - 32 * arrowDirectionUnit.x} ${v.y - 32 * arrowDirectionUnit.y}`}
        onClick={onClickCallback}
      />,
      <path
        key={`${edgeId}-h`}
        transform={`translate(${v.x},${v.y}) scale(4,4) rotate(${Math.atan2(arrowDirection.y, arrowDirection.x) * (180 / Math.PI)},0,0) translate(-9.7,-1.9)`}
        d="M0,0 V4 L4,2 Z"
        className={`fill-${edgeStyle}`}
      />,
    )
  } else {
    edge.push(
      <line
        key={`${edgeId}-e`}
        className={`stroke-${edgeStyle}`}
        strokeWidth="6"
        x1={u.x}
        y1={u.y}
        x2={v.x}
        y2={v.y}
        onClick={onClickCallback}
      />,
    )
  }

  if (weight !== undefined) {
    const weightOffset = directed ? 38 : 18
    edge.push(
      <EdgeWeight
        key={`${edgeId}-w`}
        weight={weight}
        x={center.x + normalVec.x * weightOffset}
        y={center.y + normalVec.y * weightOffset}
      />,
    )
  }

  return edge
}

/**
 * A component that returns an SVG element representing a graph.
 * @param maxWidth - The maximum width of the svg.
 * @param maxHeight - The maximum height of the svg.
 * @param graph - The graph to draw.
 */
export function DrawGraph({
  maxWidth,
  maxHeight,
  graph,
}: {
  maxWidth: number
  maxHeight: number
  graph: Graph
}): ReactElement {
  const { theme } = useTheme()
  const { lang, t } = useTranslation()

  const svgRef = useRef(null as SVGSVGElement | null)
  const coordinateScale = 60
  const nodeScale = 20

  const edgeListFlat = graph.edges
    .flat()
    .filter(graph.directed ? () => true : (e) => e.source < e.target)

  const [fieldsOpen, setFieldsOpen] = useState(false)

  const nodeInputFieldMd = `${nodeInputFieldID(graph.inputFields)}#TL###`
  const edgeInputFieldMd = `${edgeInputFieldID(graph.inputFields)}#TL###`
  let nodeField: TextFieldState | undefined
  let edgeField: TextFieldState | undefined
  if (graph.inputFields) {
    if (graph.nodeClickType !== "none") {
      addFormField(nodeInputFieldMd)
      nodeField = useFormField(`${nodeInputFieldID(graph.inputFields)}`)
    }
    if (graph.edgeClickType !== "none") {
      addFormField(edgeInputFieldMd)
      edgeField = useFormField(`${edgeInputFieldID(graph.inputFields)}`)
    }
  }

  const [currentlyDragged, setCurrentlyDragged] = useState<null | number>(null)
  const [nodePositions, setNodePositions] = useState(
    graph.nodes.map((u) => {
      return {
        x: u.coords.x * coordinateScale,
        y: u.coords.y * coordinateScale,
      }
    }),
  )
  const [nodeStates, setNodeStates] = useState<GraphElementStateType[]>(
    graph.nodes.map((u) => {
      return {
        selected: false,
        group: u.group ?? null,
      }
    }),
  )
  const [edgeStates, setEdgeStates] = useState<GraphElementStateType[]>(
    edgeListFlat.map((e) => {
      return {
        selected: false,
        group: e.group ?? null,
      }
    }),
  )

  useEffect(() => {
    saveNodeInput(nodeField, nodeStates, graph, lang)
  }, [nodeField?.text])

  useEffect(() => {
    saveEdgeInput(edgeField, edgeStates, edgeListFlat, graph, lang)
  }, [edgeField?.text])

  const edges = edgeListFlat.map((e, i) => {
    return (
      <Edge
        edgeId={`e${i}`}
        key={`e${i}`}
        u={nodePositions[e.source]}
        v={nodePositions[e.target]}
        weight={e.value}
        directed={graph.directed}
        state={edgeStates[i]}
        clickable={graph.edgeClickType !== "none" && !edgeField?.disabled}
        onClickCallback={() => {
          if (!edgeField?.disabled) {
            setEdgeStates((prevEdgeStates) => {
              const newEdgeStates = [...prevEdgeStates]
              newEdgeStates[i] = { ...prevEdgeStates[i] }
              if (graph.edgeClickType === "select") {
                newEdgeStates[i].selected = !newEdgeStates[i].selected
              } else if (graph.edgeClickType === "group") {
                newEdgeStates[i].group =
                  newEdgeStates[i].group === Math.min(graph.edgeGroupMax ?? maxGroups, maxGroups) - 1
                    ? null
                    : newEdgeStates[i].group === null
                      ? 0
                      : newEdgeStates[i].group + 1
              }
              edgeInputSetText(edgeField, newEdgeStates, edgeListFlat)
              return newEdgeStates
            })
          }
        }}
      />
    )
  })

  const nodes = graph.nodes.map((u, i) => {
    return (
      <Node
        key={`n${i}`}
        pos={nodePositions[i]}
        setDragged={
          graph.nodeDraggable
            ? () => {
                if (currentlyDragged === null) setCurrentlyDragged(i)
              }
            : undefined
        }
        size={nodeScale}
        label={u.label ?? ""}
        clickable={graph.nodeClickType !== "none" && !nodeField?.disabled}
        state={nodeStates[i]}
        // todo the onClickCallback is duplicate code.
        onClickCallback={() => {
          if (!nodeField?.disabled) {
            setNodeStates((prevNodeStates) => {
              const newNodeStates = [...prevNodeStates]
              newNodeStates[i] = { ...prevNodeStates[i] }
              if (graph.nodeClickType === "select") {
                newNodeStates[i].selected = !newNodeStates[i].selected
              } else if (graph.nodeClickType === "group") {
                newNodeStates[i].group =
                  newNodeStates[i].group === Math.min(graph.nodeGroupMax ?? maxGroups, maxGroups) - 1
                    ? null
                    : newNodeStates[i].group === null
                      ? 0
                      : newNodeStates[i].group + 1
              }
              nodeInputSetText(nodeField, newNodeStates)
              return newNodeStates
            })
          }
        }}
      />
    )
  })

  const dimensions = graph.getDimensions()
  const margin = 0.7
  const viewBox = {
    x: (dimensions.minX - margin) * coordinateScale,
    y: (dimensions.minY - margin) * coordinateScale,
    width: (dimensions.width + 2 * margin) * coordinateScale,
    height: (dimensions.height + 2 * margin) * coordinateScale,
  }

  const minViewBox = { width: 100, height: 100 }
  if (viewBox.width < minViewBox.width) {
    viewBox.x -= (minViewBox.width - viewBox.width) * 0.5
    viewBox.width = minViewBox.width
  }

  if (viewBox.height < minViewBox.height) {
    viewBox.y -= (minViewBox.height - viewBox.height) * 0.5
    viewBox.height = minViewBox.height
  }

  const viewBoxAspectRatio = Math.min(maxHeight / maxWidth, viewBox.height / viewBox.width)
  return (
    <div className={`mb-8`}>
      <div className={`relative`}>
        <svg
          ref={svgRef}
          width={maxWidth}
          height={
            viewBox.height / viewBox.width > 1 && viewBox.height < 300
              ? viewBox.height * 0.75
              : maxWidth * viewBoxAspectRatio
          }
          viewBox={`${viewBox.x} ${viewBox.y} ${viewBox.width} ${viewBox.height}`}
          className="mx-auto h-auto max-w-full rounded-lg bg-secondary pb-2"
          onMouseMove={(e) => {
            if (currentlyDragged === null || svgRef.current === null) return

            const pt = svgRef.current.createSVGPoint()
            pt.x = e.clientX
            pt.y = e.clientY
            // The cursor point, translated into svg coordinates
            const svgPos = pt.matrixTransform(svgRef.current.getScreenCTM()?.inverse())

            nodePositions[currentlyDragged].x = svgPos.x
            nodePositions[currentlyDragged].y = svgPos.y
            // react requires a new array here
            setNodePositions([...nodePositions])
          }}
          onMouseUp={() => {
            if (currentlyDragged !== null) setCurrentlyDragged(null)
          }}
        >
          <g>{edges}</g>
          <g>{nodes}</g>
        </svg>
        <div className="absolute -bottom-5 right-2 flex flex-row items-center space-x-1 rounded-lg dark:border-gray-700 dark:bg-gray-800">
          {graph.inputFields !== 0 && (
            <Toggle
              className={`${theme === "dark" ? "text-white" : "text-black"}`}
              size="sm"
              variant="bg"
              disabled={nodeField?.disabled || edgeField?.disabled}
              onClick={() => setFieldsOpen(!fieldsOpen)}
            >
              <RiInputField />
            </Toggle>
          )}
        </div>
      </div>
      {graph.nodeClickType !== "none" && fieldsOpen && (
        <div className={`mt-1`}>
          <div className={`mb-1`}>
            <b>{t("nodeSelection")}</b>
          </div>
          <div className="flex w-full flex-row items-center justify-center space-x-1">
            <div className="mr-0.5 flex-grow">
              <Markdown md={`{{${nodeInputFieldMd}}}`} />
            </div>
          </div>
        </div>
      )}
      {graph.edgeClickType !== "none" && fieldsOpen && (
        <div className={`mt-1`}>
          <div className={`mb-1`}>
            <b>{t("edgeSelection")}</b>
          </div>
          <div className="flex w-full flex-row items-center justify-center space-x-1">
            <div className="mr-0.5 flex-grow">
              <Markdown md={`{{${edgeInputFieldMd}}}`} />
            </div>
          </div>
        </div>
      )}
    </div>
  )
}

function edgeInputSetText(
  edgeField: TextFieldState | undefined,
  edgeStates: GraphElementStateType[],
  edgeListFlat: Edge[],
) {
  if (edgeField !== undefined && edgeField.setText) {
    edgeField.setText(parseEdgeText(edgeStates, edgeListFlat))
  }
}

function nodeInputSetText(nodeField: TextFieldState | undefined, nodeStates: GraphElementStateType[]) {
  if (nodeField !== undefined && nodeField.setText) {
    nodeField.setText(parseNodeText(nodeStates))
  }
}

function saveNodeInput(
  nodeField: TextFieldState | undefined,
  nodeStates: GraphElementStateType[],
  graph: Graph,
  lang: Language,
) {
  const nodeCheck = checkNodeInput(nodeField?.text ?? "", graph, lang)
  if (nodeCheck.parsed) {
    if ("selected" in nodeCheck) {
      updateGraphNodeSelected(graph, nodeStates, nodeCheck.selected)
    } else {
      updateGraphNodeGroup(graph, nodeStates, nodeCheck.groups)
    }
  }
}

function saveEdgeInput(
  edgeField: TextFieldState | undefined,
  edgeStates: GraphElementStateType[],
  edgeListFlat: Edge[],
  graph: Graph,
  lang: Language,
) {
  const edgeCheck = checkEdgeInput(edgeField?.text ?? "", graph, lang)
  if (edgeCheck.parsed) {
    if ("selected" in edgeCheck) {
      updateGraphEdgeSelected(graph.directed, edgeListFlat, edgeStates, edgeCheck.selected)
    } else {
      updateGraphEdgeGroup(graph.directed, edgeListFlat, edgeStates, edgeCheck.groups)
    }
  }
}
