// packages/svelte-front-end/src/lib/components/markdown.svelte
<script lang="ts">
  import TeX from "$lib/components/TeX.svelte"
  import FormInputField from "$lib/components/ui/MultiInput/FormInputField.svelte"
  import type { Snippet } from "svelte"
  import { parseMarkdown, type ParseTree, type ParseTreeNode } from "@shared/utils/parseMarkdown"

  interface Props {
    md: string
    child0?: Snippet<[]>
    child1?: Snippet<[]>
    child2?: Snippet<[]>
    child3?: Snippet<[]>
    child4?: Snippet<[]>
    child5?: Snippet<[]>
  }

  const props: Props = $props()
  const t = $derived(parseMarkdown(props.md))
</script>

{#snippet tree(t: ParseTree, props: Props)}
  {#each t as n}
    {@render node(n, props)}
  {/each}
{/snippet}

{#snippet node(x: ParseTreeNode, props: Props)}
  {#if typeof x === "string"}
    {#each x.split(/(\{\{\d+\}\})/) as y}
      {#if y === "{{0}}"}
        {@render props.child0?.()}
      {:else if y === "{{1}}"}
        {@render props.child1?.()}
      {:else if y === "{{2}}"}
        {@render props.child2?.()}
      {:else if y === "{{3}}"}
        {@render props.child3?.()}
      {:else if y === "{{4}}"}
        {@render props.child4?.()}
      {:else if y === "{{5}}"}
        {@render props.child5?.()}
      {:else}
        {y}
      {/if}
    {/each}
  {:else if x.kind === "`"}
    <span class="rounded-sm bg-gray-200 px-2 py-1 font-mono dark:bg-gray-700">{x}</span>
  {:else if x.kind === "```"}
    <!-- TODO -->
    <pre class="block">{x}</pre>
  {:else if x.kind === "$$" || x.kind === "$"}
    <TeX expr={x.child} displayMode={x.kind === "$$"} />
  {:else if x.kind === "**"}
    <strong>{@render tree(x.child, props)}</strong>
  {:else if x.kind === "*"}
    <em>{@render tree(x.child, props)}</em>
  {:else if x.kind === ">"}
    <blockquote class="my-4 border-l-4 pl-2">{@render tree(x.child, props)}</blockquote>
  {:else if x.kind === "a"}
    <a href={x.url}>{@render tree(x.child, props)}</a>
  {:else if x.kind === "list"}
    <ul>
      {#each x.child as c}
        <li>{@render node(c.text, props)}</li>
      {/each}
    </ul>
  {:else if x.kind === "input"}
    <FormInputField id={x.child.split("#")[0]} />
  {:else}
    TODO: Rendering of Markdown nodes <pre>{x.kind}</pre>
    is not yet implemented.
  {/if}
{/snippet}

{@render tree(t, props)}

// front-end/src/components/Markdown.tsx
import { Fragment, FunctionComponent, ReactNode } from "react"
import { Link } from "react-router-dom"
import { parseMarkdown, ParseTree, ParseTreeNode } from "@shared/utils/parseMarkdown.ts"
import { DrawList } from "@/components/DrawList.tsx"
import { DrawPseudoCode } from "@/components/DrawPseudoCode.tsx"
import { DrawTable } from "@/components/DrawTable.tsx"
import { MatrixInput } from "@/components/MatrixInput.tsx"
import { FormInputField } from "@/components/ui/FormInputField.tsx"
import { Format } from "./Format"
import TeX from "./TeX"

/**
 * Function to render a given markdown-like string as a React component
 *
 * @param props
 * @param props.md The markdown-like string to render
 * @param props.children The parameters to replace the mustache-style placeholders in the string
 * @returns The React component
 */
export const Markdown: FunctionComponent<{
  md?: string
  children?: ReactNode[]
}> = ({ md, children }) => {
  if (!md) {
    return <></>
  }
  return <MarkdownTree parseTree={parseMarkdown(md)} parameters={children} />
}

/**
 * Function to render a given parseTree as a React component
 *
 * @param props
 * @param props.parseTree The parse tree to render
 * @returns The React component
 */
export const MarkdownTree: FunctionComponent<{
  parseTree: ParseTree
  parameters?: ReactNode[]
}> = ({ parseTree, parameters }) => {
  // TODO: Implement this function
  return (
    <>
      {parseTree.map((node, index) => (
        <Fragment key={index}>
          <MarkdownTreeNode parseTreeNode={node} parameters={parameters} />
        </Fragment>
      ))}
    </>
  )
}

/**
 * Function to render a given parseTreeNode as a React component
 *
 * @param props
 * @param props.parseTreeNode The parse tree node to render
 * @returns The React component
 */
export const MarkdownTreeNode: FunctionComponent<{
  parseTreeNode: ParseTreeNode
  parameters?: ReactNode[]
}> = ({ parseTreeNode, parameters }) => {
  if (typeof parseTreeNode === "string") {
    return <Format template={parseTreeNode} parameters={parameters} />
  }
  if (parseTreeNode.kind === "$$") {
    return <TeX tex={parseTreeNode.child} block />
  }
  if (parseTreeNode.kind === "$") {
    return <TeX tex={parseTreeNode.child} />
  }
  if (parseTreeNode.kind === "**") {
    return (
      <b>
        <MarkdownTree parseTree={parseTreeNode.child} />
      </b>
    )
  }
  if (parseTreeNode.kind === "*") {
    return (
      <i>
        <MarkdownTree parseTree={parseTreeNode.child} />
      </i>
    )
  }
  if (parseTreeNode.kind === "`") {
    return (
      <span className="rounded-sm bg-gray-200 px-2 py-1 font-mono dark:bg-gray-700">
        {format(parseTreeNode.child, parameters)}
      </span>
    )
  }
  if (parseTreeNode.kind === "```") {
    if (parseTreeNode.language === "pseudoCode") {
      return <DrawPseudoCode displayCode={parseTreeNode.child} />
    }
    if (parseTreeNode.language === "matrixInput") {
      return <MatrixInput matrixObject={parseTreeNode.child} />
    }
    throw new Error("Unknown language")
  }
  if (parseTreeNode.kind === "table") {
    return <DrawTable table={parseTreeNode.child} />
  }
  if (parseTreeNode.kind === "list") {
    return <DrawList list={parseTreeNode.child} />
  }
  if (parseTreeNode.kind === "a") {
    return (
      <Link to={format(parseTreeNode.url, parameters)}>
        <MarkdownTree parseTree={parseTreeNode.child} parameters={parameters} />
      </Link>
    )
  }
  if (parseTreeNode.kind === ">") {
    return (
      <blockquote className="my-4 border-l-4 pl-2">
        <MarkdownTree parseTree={parseTreeNode.child} />
      </blockquote>
    )
  }
  if (parseTreeNode.kind === "input") {
    // only provide the id of the input field
    const inputSplit = parseTreeNode.child.split("#")
    const id = inputSplit[0]

    return <FormInputField id={id} />
  }

  // will never be reached:
  return <></>
}

function format(text: string, parameters?: ReactNode[]): string {
  if (parameters) {
    parameters.forEach((p, index) => {
      if (typeof p === "string") {
        text = text.replace(`{{${index}}}`, p)
      }
    })
  }
  return text
}
