// packages/svelte-front-end/src/lib/components/QuestionComponent.svelte
<script lang="ts">
  import ExerciseMultipleChoice from "$lib/components/ExerciseMultipleChoice.svelte"
  import ExerciseMultiTextInput from "$lib/components/ExerciseMultiTextInput.svelte"
  import ExerciseTextInput from "$lib/components/ExerciseTextInput.svelte"
  import type { Result } from "$lib/components/types.ts"
  import type { Language } from "@shared/api/Language.ts"
  import type { Question } from "@shared/api/QuestionGenerator.ts"

  interface Props {
    question: Question
    onResult?: (result: Result) => void
    regenerate?: () => void
    lang: Language
  }
  const { question, onResult, regenerate, lang }: Props = $props()
</script>

{#if question.type === "MultipleChoiceQuestion"}
  <ExerciseMultipleChoice {question} permalink={question.path} {onResult} {regenerate} {lang} />
{:else if question.type === "FreeTextQuestion"}
  <ExerciseTextInput {question} permalink={question.path} {onResult} {regenerate} {lang} />
{:else if question.type === "MultiFreeTextQuestion"}
  <ExerciseMultiTextInput {question} permalink={question.path} {onResult} {regenerate} {lang} />
{:else}
  <b>Unsupported question type.</b>
{/if}

// front-end/src/components/QuestionComponent.tsx
import { FunctionComponent } from "react"
import { Question } from "@shared/api/QuestionGenerator"
import { ExerciseMultipleChoice } from "./ExerciseMultipleChoice"
import { ExerciseMultiTextInput } from "./ExerciseMultiTextInput.tsx"
import { ExerciseTextInput } from "./ExerciseTextInput"

/** Props for the React Component */
export interface QuestionComponentProps {
  /** The question object, or a promise for the question object. */
  question: Question

  /** Callback for when a result is produced */
  onResult?: (result: Result) => void

  /** Optional callback to regenerate the question */
  regenerate?: () => void

  // viewOnly?: boolean // Determines whether the component should displayed interactively or non-interactively
  // source?: boolean // If true, display the LaTeX source code of the question
}

/** Result type for exercise results */
export type Result = "correct" | "incorrect" | "abort" | "timeout"

/** Function to render the question as a React component */
export const QuestionComponent: FunctionComponent<QuestionComponentProps> = ({
  question,
  onResult,
  regenerate,
}) => {
  if (question.type === "MultipleChoiceQuestion") {
    return (
      <ExerciseMultipleChoice
        question={question}
        regenerate={regenerate}
        onResult={onResult}
        permalink={question.path}
      />
    )
  } else if (question.type === "FreeTextQuestion") {
    return (
      <ExerciseTextInput
        question={question}
        regenerate={regenerate}
        onResult={onResult}
        permalink={question.path}
      />
    )
  } else if (question.type === "MultiFreeTextQuestion") {
    return (
      <ExerciseMultiTextInput
        question={question}
        regenerate={regenerate}
        onResult={onResult}
        permalink={question.path}
      />
    )
  }
  return <>Unsupported question type.</>
}
