// packages/svelte-front-end/src/lib/components/QuestionHeader.svelte
<script lang="ts">
  import { browser } from "$app/environment"
  import MyTooltip from "$lib/components/ui/MyTooltip.svelte"
  import { prefixURL } from "$lib/config.js"
  import { globalTranslations } from "$lib/translation.ts"
  import { getLanguage } from "$lib/utils/langState.svelte.ts"
  import { Tooltip } from "bits-ui"
  import { Link, RefreshCwIcon } from "lucide-svelte"
  import type { Language } from "@shared/api/Language.ts"
  import { tFunction } from "@shared/utils/translations.ts"

  interface Props {
    title?: string
    regenerate?: () => void
    permalink?: string
  }

  const { title, regenerate, permalink }: Props = $props()
  const lang: Language = $derived(getLanguage())
  const { t } = $derived(tFunction([globalTranslations], lang))
  let recentlyCopied: boolean = $state(false)

  function handleClick() {
    if (!browser) return
    void navigator.clipboard.writeText(prefixURL + "/" + permalink).then(() => {
      recentlyCopied = true
    })
  }

  function mouseLeave() {
    recentlyCopied = false
  }
</script>

<h1 class="text-2xl font-semibold">
  {title !== undefined && title + " "}
  {#if permalink}
    <Tooltip.Provider>
      <MyTooltip
        open={recentlyCopied}
        contentProps={{ sideOffset: 5 }}
        triggerProps={{ onclick: handleClick, onmouseleave: mouseLeave }}
      >
        {#snippet trigger()}
          <Link class="pl-1" />
        {/snippet}
        {(recentlyCopied ? t("copyLinkCopied") : t("copyLinkTooltip")) || ""}
      </MyTooltip>
    </Tooltip.Provider>
  {/if}
  {#if regenerate}
    <Tooltip.Provider>
      <MyTooltip contentProps={{ sideOffset: 5 }} triggerProps={{ onclick: regenerate }}>
        {#snippet trigger()}
          <RefreshCwIcon class="pl-1" size={20} strokeWidth={1.5} absoluteStrokeWidth />
        {/snippet}
        {t("generate-new-exercise-of-same-type")}
      </MyTooltip>
    </Tooltip.Provider>
  {/if}
</h1>

// front-end/src/components/QuestionHeader.tsx
import { useState } from "react"
import { BiLink, BiRefresh } from "react-icons/bi"
import { Tooltip, TooltipContent, TooltipTrigger } from "@/components/ui/tooltip"
import { prefixURL } from "../config"
import { useTranslation } from "../hooks/useTranslation"
import { Button } from "./ui/button"

/**
 * QuestionHeader is a header for a question.
 *
 * @param props
 * @param props.title Title of the question.
 * @param props.regenerate Function to regenerate the question.
 * @param props.permalink Permalink to the question.
 */
export function QuestionHeader({
  title,
  regenerate,
  permalink,
}: {
  title?: string
  regenerate?: () => void
  permalink?: string
}) {
  const { t } = useTranslation()
  const [recentlyCopied, setRecentlyCopied] = useState(false)
  return (
    <h1 className="text-2xl font-bold">
      {title != undefined && title + " "}
      {permalink && (
        <Tooltip placement="right">
          <TooltipTrigger asChild>
            <Button
              className="inline text-2xl"
              size={"icon"}
              variant={"link"}
              onClick={() => {
                void navigator.clipboard
                  .writeText(prefixURL + "/" + permalink)
                  .then(() => setRecentlyCopied(true))
              }}
              onMouseLeave={() => {
                setTimeout(() => setRecentlyCopied(false), 200)
              }}
            >
              <BiLink className="inline" />
            </Button>
          </TooltipTrigger>
          <TooltipContent>
            {(recentlyCopied ? t("copyLinkCopied") : t("copyLinkTooltip")) || ""}
          </TooltipContent>
        </Tooltip>
      )}
      {regenerate && (
        <Tooltip placement="right">
          <TooltipTrigger asChild>
            <button type="button" onClick={regenerate}>
              <BiRefresh className="inline" />
            </button>
          </TooltipTrigger>
          <TooltipContent>{t("generate-new-exercise-of-same-type")}</TooltipContent>
        </Tooltip>
      )}
    </h1>
  )
}
