// src/components/ExerciseMultipleChoice.tsx
import { useState } from "react"
import { AnswerBox } from "./AnswerBox"
import { Question } from "./Question"
import useGlobalDOMEvents from "../hooks/useGlobalDOMEvents"
import { useSound } from "../hooks/useSound"
import {
  MultipleChoiceFeedback,
  MultipleChoiceQuestion,
} from "../api/QuestionGenerator"
import { Markdown } from "./Markdown"
import { Result } from "./QuestionComponent"

/** The current display mode */
export type MODE =
  | "invalid" // Invalid selection (e.g. nothing selected), "Check" button is disabled
  | "draft" // Valid selection (e.g. at least one answer), but not yet submitted
  | "submitted" // "Check" was clicked, feedback was requested
  | "correct" // According to the feedback, the answer was correct
  | "incorrect" // According to the feedbackm, the answer was incorrect

/**
 * ExerciseMultipleChoice is a multiple choice exercise.
 *
 * @param props
 * @param props.question The question.
 * @param props.permalink Permalink to the question (optional)
 * @param props.onResult Function to call after (optional)
 * @param props.regenerate Function to regenerate the question (optional)
 * @param props.viewOnly Whether the exercise is in view-only mode (optional)
 */
export function ExerciseMultipleChoice({
  question,
  permalink,
  onResult,
  regenerate,
  viewOnly = false,
}: {
  question: MultipleChoiceQuestion
  permalink?: string
  onResult?: (result: Result) => void
  regenerate?: () => void
  viewOnly?: boolean
}) {
  const { playSound } = useSound()

  const [state, setState] = useState({
    mode: "invalid" as MODE,

    /** The indices of the selected answers */
    choice: [] as Array<number>,

    /** The feedback object returned by question.feedback() */
    feedbackObject: undefined as MultipleChoiceFeedback | undefined,
  })

  const { mode, choice, feedbackObject } = state

  /**
   * SetChoiceEntry sets the choice for a single entry.
   *
   * @param key The index of the entry
   * @param value Whether the entry should be chosen
   */
  function setChoiceEntry(key: number, value: boolean) {
    const newChoice = question.allowMultiple
      ? choice.filter((x) => x !== key)
      : []
    if (value) {
      newChoice.push(key)
    }
    setState({
      ...state,
      mode: newChoice.length === 0 ? "invalid" : "draft",
      choice: newChoice.sort(),
    })
  }

  function handleClick() {
    if (mode === "invalid") {
      return
    } else if (mode === "draft") {
      if (question.feedback !== undefined) {
        setState({ ...state, mode: "submitted" })
        void Promise.resolve(question.feedback({ choice: choice })).then(
          (feedbackObject) => {
            let mode: MODE = "draft"
            if (feedbackObject.correct === true) {
              playSound("pass")
              mode = "correct"
            } else if (feedbackObject.correct === false) {
              playSound("fail")
              mode = "incorrect"
            }
            setState({ ...state, mode, feedbackObject })
          }
        )
      }
    } else if (mode === "correct" || mode === "incorrect") {
      onResult && onResult(mode)
    }
  }

  useGlobalDOMEvents({
    keydown(e: Event) {
      const kbEvent = e as KeyboardEvent
      if (kbEvent.ctrlKey || kbEvent.metaKey || kbEvent.altKey) {
        return
      }

      if (kbEvent.key === "Enter") {
        e.preventDefault()
        handleClick()
        return
      }
      if (mode === "correct" || mode === "incorrect") {
        return
      }
      const num = parseInt(kbEvent.key)
      if (!Number.isNaN(num) && num >= 1 && num <= question.answers.length) {
        e.preventDefault()
        const id = num - 1 // answers[num - 1].key
        setChoiceEntry(id, !choice.includes(id))
        return
      }
    },
  })
  let message = null
  if (mode === "correct") {
    message = <b className="text-2xl">Correct!</b>
  } else if (mode === "incorrect") {
    message = feedbackObject?.correctChoice ? (
      <>
        <b className="text-xl">
          Correct solution
          {feedbackObject.correctChoice.length > 1 ? "s" : ""}:
        </b>
        <br />
        {feedbackObject.correctChoice.map((item, index) => (
          <div key={index}>{<Markdown md={question.answers[item]} />}</div>
        ))}
      </>
    ) : (
      <>Incorrect</>
    )
  }
  return (
    <Question
      permalink={permalink}
      title={question.name}
      regenerate={regenerate}
      footerMode={
        mode === "invalid" || viewOnly
          ? "disabled"
          : mode === "correct"
          ? "correct"
          : mode === "incorrect"
          ? "incorrect"
          : "verify"
      }
      footerMessage={message}
      handleFooterClick={handleClick}
    >
      <Markdown md={question.text ?? ""} />
      <div className="mx-auto flex max-w-max flex-wrap gap-5 p-5">
        {question.answers.map((answer, index) => {
          const id = `${index}`
          return (
            <div key={index} className="flex place-items-center">
              <input
                type={question.allowMultiple ? "checkbox" : "radio"}
                id={id}
                className="peer hidden"
                checked={choice.includes(index)}
                onChange={(e) => {
                  setChoiceEntry(parseInt(e.target.id, 10), e.target.checked)
                }}
                disabled={mode === "correct" || mode === "incorrect"}
              />
              <AnswerBox
                checked={choice.includes(index)}
                correct={feedbackObject?.correctChoice?.includes(index)}
                disabled={mode === "correct" || mode === "incorrect"}
                TagName="label"
                htmlFor={id}
                className="relative"
              >
                <Markdown md={answer} />
              </AnswerBox>
            </div>
          )
        })}
      </div>
    </Question>
  )
}

// packages/svelte-front-end/src/lib/components/ExerciseMultipleChoice.svelte
<script lang="ts">
  import InteractWithQuestion from "$lib/components/InteractWithQuestion.svelte"
  import Markdown from "$lib/components/markdown.svelte"
  import type { MODE, Result } from "$lib/components/types.ts"
  import { Checkbox } from "$lib/components/ui/checkbox"
  import { Label } from "$lib/components/ui/label"
  import { playSound } from "$lib/sound.svelte.ts"
  import { globalTranslations } from "$lib/translation.ts"
  import { Tooltip } from "bits-ui"
  import { CheckCheck, XCircle } from "lucide-svelte"
  import type { Snippet } from "svelte"
  import type { Language } from "@shared/api/Language.ts"
  import type { MultipleChoiceFeedback, MultipleChoiceQuestion } from "@shared/api/QuestionGenerator.ts"
  import { tFunction } from "@shared/utils/translations.ts"

  interface Props {
    question: MultipleChoiceQuestion
    permalink?: string
    onResult?: (result: Result) => void
    regenerate?: () => void
    lang: Language
  }

  const { question, permalink, onResult, regenerate, lang }: Props = $props()
  const { t } = $derived(tFunction([globalTranslations], lang))

  let questionState: {
    mode: MODE
    choice: Array<number>
    feedbackObject?: MultipleChoiceFeedback
  } = $state({
    mode: question.sorting ? "draft" : "invalid",
    choice: question.sorting ? [...Array(question.answers.length).keys()] : [],
  })
  const disabled: boolean = $state(
    questionState.mode === "correct" || questionState.mode === "incorrect",
  )

  /**
   * SetChoice sets the entire choice array.
   *
   * @param newChoice The new choice array
   */
  function setChoice(newChoice: Array<number>): void {
    questionState.choice = newChoice
  }

  /**
   * SetChoiceEntry sets the choice for a single entry.
   *
   * @param key The index of the entry
   * @param value Whether the entry should be chosen
   */
  function setChoiceEntry(key: number, value: boolean): void {
    const newChoice = question.allowMultiple ? questionState.choice.filter((x) => x !== key) : []
    if (value) {
      newChoice.push(key)
    }
    questionState.mode = newChoice.length === 0 ? "invalid" : "draft"
    questionState.choice = newChoice.sort()
  }

  function handleClick() {
    if (questionState.mode === "draft") {
      if (question.feedback !== undefined) {
        questionState.mode = "submitted"
        void Promise.resolve(question.feedback({ choice: questionState.choice })).then(
          (feedbackObject) => {
            let mode: MODE = "draft"
            if (feedbackObject.correct === true) {
              playSound("pass")
              mode = "correct"
            } else if (feedbackObject.correct === false) {
              playSound("fail")
              mode = "incorrect"
            }
            questionState.mode = mode
            questionState.feedbackObject = feedbackObject
          },
        )
      }
    } else if (questionState.mode === "correct" || questionState.mode === "incorrect") {
      if (onResult) onResult(questionState.mode)
    }
  }

  // Todo: Add some equivalent svelte
  // useGlobalDOMEvents({
  //   keydown(e: Event) {
  //     if (!(e instanceof KeyboardEvent)) return
  //     if (e.ctrlKey || e.metaKey || e.altKey) return
  //     if (e.key === "Enter") {
  //       e.preventDefault()
  //       handleClick()
  //       return
  //     }
  //     if (state.mode === "correct" || state.mode === "incorrect") return
  //
  //     if (!question.sorting) {
  //       const num = parseInt(e.key)
  //       if (!Number.isNaN(num) && num >= 1 && num <= question.answers.length) {
  //         e.preventDefault()
  //         const id = num - 1 // answers[num - 1].key
  //         setChoiceEntry(id, !state.choice.includes(id))
  //         return
  //       }
  //     }
  //   },
  // })

  const messages: Array<Snippet> = []
  if (!question.sorting) {
    if (questionState.mode === "correct") {
      // Todo: Check if this is an error or WebStorm just sucks???
      messages.push(correct())
    } else if (questionState.mode === "incorrect") {
      messages.push(questionState.feedbackObject?.correctChoice ? correctSolution() : incorrect())
    }
    if (questionState.feedbackObject?.feedbackText)
      messages.push(feedbackText(questionState.feedbackObject.feedbackText))
  } else {
    // Todo: Missing sorting
  }
</script>

{#if !question.sorting}
  <InteractWithQuestion
    {permalink}
    name={question.name}
    {regenerate}
    footerMode={questionState.mode}
    footerMessage={messages}
    {lang}
    handleFooterClick={handleClick}
  >
    <Markdown md={question.text ?? ""} />
    <div class="flex flex-col flex-wrap gap-4 p-4">
      {#each question.answers as answer, index}
        <div class="flex items-center space-x-2">
          {@render FeedbackIconAndTooltip(
            true === questionState.feedbackObject?.correctChoice?.includes(index),
            (true === questionState.feedbackObject?.correctChoice?.includes(index)) ===
              questionState.choice.includes(index),
            !disabled,
          )}
          <Checkbox
            id={index.toString()}
            checked={questionState.choice.includes(index)}
            {disabled}
            onCheckedChange={() => {
              setChoiceEntry(index, !questionState.choice.includes(index))
            }}
          />
          <div class="grid gap-1.5 leading-none">
            <Label>
              <Markdown md={answer} />
            </Label>
          </div>
        </div>
      {/each}
    </div>
  </InteractWithQuestion>
{:else}
  <!-- Todo: Sorting Questions -->
  Not implemented
{/if}

{#snippet correct()}
  <b class="text-2xl">Correct!</b>
{/snippet}

{#snippet incorrect()}
  <b class="text-2xl">{t("incorrect")}</b>
{/snippet}

{#snippet correctSolution()}
  <b class="text-xl">{t("correct.solution")}:</b>
  <br />
  {t("see.above")}
  <br />
{/snippet}

{#snippet feedbackText(text: string)}
  <Markdown md={text} />
{/snippet}

{#snippet FeedbackIconAndTooltip(
  isCorrectAnswer: boolean,
  userGaveCorrectAnswer: boolean,
  hidden: boolean,
)}
  <Tooltip.Provider>
    <Tooltip.Root>
      <Tooltip.Trigger>
        {@render FeedbackIcon(isCorrectAnswer, hidden)}
      </Tooltip.Trigger>
      <Tooltip.Content>
        {isCorrectAnswer ? t("answer.correct") : t("answer.wrong")}
        <br />
        {userGaveCorrectAnswer ? t("choice.correct") : t("choice.wrong")}
      </Tooltip.Content>
    </Tooltip.Root>
  </Tooltip.Provider>
{/snippet}

{#snippet FeedbackIcon(correct: boolean, hidden: boolean)}
  {#if correct}
    <CheckCheck class={"h-4 w-4 text-green-700" + (hidden ? " invisible" : "")} />
  {:else}
    <XCircle class={"h-4 w-4 text-green-700" + (hidden ? " invisible" : "")} />
  {/if}
{/snippet}
