// front-end/src/components/ExerciseTextInput.tsx
import { useEffect, useRef, useState } from "react"
import { FreeTextFeedback, FreeTextQuestion } from "@shared/api/QuestionGenerator.ts"
import { Button } from "@/components/ui/button"
import { Input } from "@/components/ui/input"
import { isMobileOrTablet } from "@/utils/deviceInformation.ts"
import useGlobalDOMEvents from "../hooks/useGlobalDOMEvents"
import { useSound } from "../hooks/useSound"
import { useTranslation } from "../hooks/useTranslation"
import { InteractWithQuestion, MODE } from "./InteractWithQuestion"
import { Markdown } from "./Markdown"
import { Result } from "./QuestionComponent"

/**
 * ExerciseTextInput is an exercise that requires the user to type in text.
 *
 * @param props
 * @param props.question The question.
 * @param props.regenerate Function to regenerate the question.
 * @param props.onResult Function to call when the user submits an answer.
 * @param props.permalink Permalink to the question.
 */
export function ExerciseTextInput({
  question,
  regenerate,
  onResult,
  permalink,
}: {
  question: FreeTextQuestion
  regenerate?: () => void
  onResult?: (result: Result) => void
  permalink?: string
}) {
  const { playSound } = useSound()
  const { t } = useTranslation()

  const [state, setState] = useState<{
    /** The current state of the exercise interaction */
    mode: MODE

    /** The current input text */
    text: string

    /**
     * The feedback object returned by question.feedback(). Will be set when the
     * Promise returned by question.feedback() resolves.
     */
    feedbackObject?: FreeTextFeedback

    /**
     * Message to show when the text is invalid. This is determined by the
     * checkFormat method.
     */
    formatFeedback?: string
  }>({
    mode: "invalid",
    text: "",
  })

  const { mode, text, feedbackObject, formatFeedback } = state

  const userInputRef = useRef<HTMLInputElement>(null)

  useEffect(() => {
    if (!isMobileOrTablet) {
      userInputRef.current?.focus({ preventScroll: true })
    }
  }, [])

  function setText(text: string) {
    setState((state) => ({ ...state, text }))
    if (question.checkFormat) {
      void Promise.resolve(question.checkFormat({ text })).then(({ valid, message }) => {
        setState({
          ...state,
          text,
          mode: valid ? "draft" : "invalid",
          formatFeedback: message,
        })
      })
    } else {
      const valid = text.trim().length > 0
      setState({ ...state, text, mode: valid ? "draft" : "invalid" })
    }
  }

  function insertText(text: string): void {
    if (userInputRef.current === null) {
      setText(text)
      return
    }

    setText(
      userInputRef.current.value.slice(0, userInputRef.current.selectionStart ?? 0) +
        text +
        userInputRef.current.value.slice(userInputRef.current.selectionEnd ?? 0),
    )

    userInputRef.current.focus()
  }

  function handleClick() {
    if (mode === "draft") {
      if (question.feedback !== undefined) {
        setState({ ...state, mode: "submitted" })
        void Promise.resolve(question.feedback({ text })).then((feedbackObject) => {
          let mode: MODE = "draft"
          if (feedbackObject.correct === true) {
            playSound("pass")
            mode = "correct"
          } else if (feedbackObject.correct === false) {
            playSound("fail")
            mode = "incorrect"
          }
          setState({ ...state, mode, feedbackObject })
        })
      }
    } else if (mode === "correct" || mode === "incorrect") {
      if (onResult) onResult(mode)
    }
  }

  useGlobalDOMEvents({
    keydown(e: Event) {
      if (!(e instanceof KeyboardEvent)) {
        return
      }
      const key = e.key
      if (key === "Enter") {
        e.preventDefault()
        handleClick()
      }
    },
  })

  const msgColor =
    mode === "draft" ? "text-green-600 dark:text-green-400" : "text-red-600 dark:text-red-400"

  const message = []
  if (mode === "correct") {
    message.push(<b className="text-2xl">{t("feedback.correct")}</b>)
  } else if (mode === "incorrect") {
    if (feedbackObject?.feedbackText) {
      message.push(
        <>
          <Markdown md={feedbackObject.feedbackText} />
          <br />
        </>,
      )
    }
    if (feedbackObject?.correctAnswer) {
      message.push(
        <>
          <b className="text-xl">{t("feedback.possible-correct-solution")}:</b>
          <br />
          <Markdown md={feedbackObject.correctAnswer} />
        </>,
      )
    } else {
      message.push(<b className="text-2xl">{t("feedback.incorrect")}</b>)
    }
  }

  return (
    <InteractWithQuestion
      permalink={permalink}
      name={question.name}
      regenerate={regenerate}
      footerMode={mode}
      footerMessage={message}
      handleFooterClick={handleClick}
    >
      <Markdown md={question.text} />
      <br />
      <br />
      <div className="flex place-items-center gap-2 pl-3">
        <Markdown md={question.prompt} />
        <Input
          ref={userInputRef}
          disabled={mode === "correct" || mode === "incorrect"}
          value={text}
          onChange={(e) => {
            setText(e.target.value)
          }}
          type="text"
          placeholder={question.placeholder}
        />
        <div className={`flex h-12 items-center ${msgColor}`}>
          <div>
            <Markdown md={formatFeedback} />
          </div>
        </div>
      </div>
      <div className="py-5 text-slate-600 dark:text-slate-400">
        <Markdown md={question.bottomText} />
      </div>
      <div className="flex flex-wrap gap-2">
        {(question.typingAid ?? []).map((el, index) => (
          <Button
            variant="secondary"
            key={`ta-${index}`}
            onClick={() => insertText(el.input)}
            aria-label={t("typing-aid.label", [el.label])}
          >
            <Markdown md={el.text} />
          </Button>
        ))}
      </div>
    </InteractWithQuestion>
  )
}

// packages/svelte-front-end/src/lib/components/ExerciseTextInput.svelte
<script lang="ts">
  import InteractWithQuestion from "$lib/components/InteractWithQuestion.svelte"
  import Markdown from "$lib/components/markdown/markdown.svelte"
  import type { MODE, Result } from "$lib/components/types.ts"
  import { Button } from "$lib/components/ui/button"
  import { inputClass } from "$lib/components/ui/input/cnInput.ts"
  import { playSound } from "$lib/sound.svelte.ts"
  import { globalTranslations } from "$lib/translation.ts"
  import { isMobileOrTablet } from "$lib/utils/deviceInformation.ts"
  import { onMount } from "svelte"
  import type { Language } from "@shared/api/Language.ts"
  import type { FreeTextFeedback, FreeTextQuestion } from "@shared/api/QuestionGenerator.ts"
  import { tFunction } from "@shared/utils/translations.ts"

  interface Props {
    question: FreeTextQuestion
    permalink?: string
    onResult?: (result: Result) => void
    regenerate?: () => void
    lang: Language
  }
  const { question, permalink, onResult, regenerate, lang }: Props = $props()
  const { t } = $derived(tFunction([globalTranslations], lang))

  let questionState: {
    mode: MODE
    text: string
    feedbackObject?: FreeTextFeedback
    formatFeedback?: string
  } = $state({
    mode: "invalid",
    text: "",
  })

  let userInputRef: HTMLInputElement | null = $state(null)
  onMount(() => {
    if (!isMobileOrTablet) {
      userInputRef!.focus({ preventScroll: true })
    }
  })

  function handleChange(event: Event) {
    setText((event.target as HTMLInputElement).value)
  }

  function setText(text: string) {
    questionState = {
      ...questionState,
      text,
    }
    if (question.checkFormat) {
      void Promise.resolve(question.checkFormat({ text })).then(({ valid, message }) => {
        questionState = {
          ...questionState,
          mode: valid ? "draft" : "invalid",
          formatFeedback: message,
        }
      })
    } else {
      questionState = {
        ...questionState,
        mode: text.trim().length > 0 ? "draft" : "invalid",
      }
    }
  }

  function insertText(text: string): void {
    if (userInputRef === null) {
      setText(text)
      return
    }

    setText(
      userInputRef.value.slice(0, userInputRef.selectionStart ?? 0) +
        text +
        userInputRef.value.slice(userInputRef.selectionEnd ?? 0),
    )

    userInputRef.focus()
  }

  function handleClick() {
    if (questionState.mode === "draft") {
      if (question.feedback !== undefined) {
        questionState.mode = "submitted"
        void Promise.resolve(question.feedback({ text: questionState.text })).then((feedbackObject) => {
          let mode: MODE = "draft"
          if (feedbackObject.correct === true) {
            playSound("pass")
            mode = "correct"
          } else if (feedbackObject.correct === false) {
            playSound("fail")
            mode = "incorrect"
          }
          questionState.mode = mode
          questionState.feedbackObject = feedbackObject
        })
      }
    } else if (questionState.mode === "correct" || questionState.mode === "incorrect") {
      if (onResult) onResult(questionState.mode)
    }
  }

  function onKeyDown(e: Event) {
    if (!(e instanceof KeyboardEvent)) {
      return
    }
    const key = e.key
    if (key === "Enter") {
      e.preventDefault()
      handleClick()
    }
  }

  const msgColor = $derived(
    questionState.mode === "draft"
      ? "text-green-600 dark:text-green-400"
      : "text-red-600 dark:text-red-400",
  )
</script>

<InteractWithQuestion
  {permalink}
  name={question.name}
  {regenerate}
  footerMode={questionState.mode}
  footerMessage={messageList}
  {lang}
  handleFooterClick={handleClick}
>
  <Markdown md={question.text ?? ""} />
  <br />
  <br />
  <div class="flex place-items-center gap-2 pl-3">
    <Markdown md={question.prompt ?? ""} />
    <input
      class="${inputClass}"
      bind:this={userInputRef}
      disabled={questionState.mode === "correct" || questionState.mode === "incorrect"}
      value={questionState.text}
      oninput={handleChange}
      type="text"
      placeholder={question.placeholder}
    />
    <div class={`flex h-12 items-center ${msgColor}`}>
      <div>
        <Markdown md={questionState.formatFeedback ?? ""} />
      </div>
    </div>
  </div>
  <div class="py-5 text-slate-600 dark:text-slate-400">
    <Markdown md={question.bottomText ?? ""} />
  </div>
  <div class="flex flex-wrap gap-2">
    {#each question.typingAid ?? [] as el}
      <Button
        variant="secondary"
        onclick={() => insertText(el.input)}
        aria-label={t("typing-aid.label", [el.label])}
      >
        <Markdown md={el.text ?? ""} />
      </Button>
    {/each}
  </div>
</InteractWithQuestion>

{#snippet messageList()}
  <div class="flex-col">
    {#if questionState.mode === "correct"}
      {@render correct()}
    {:else if questionState.mode === "incorrect"}
      {#if questionState.feedbackObject?.feedbackText}
        {@render feedbackText()}
      {/if}
      {#if questionState.feedbackObject?.correctAnswer}
        {@render correctAnswer()}
      {/if}
    {:else}
      {@render incorrect()}
    {/if}
  </div>
{/snippet}

{#snippet correct()}
  <b class="text-2xl">{t("feedback.correct")}</b>
{/snippet}

{#snippet incorrect()}
  <b class="text-2xl">{t("incorrect")}</b>
{/snippet}

{#snippet feedbackText()}
  <Markdown md={questionState.feedbackObject?.feedbackText ?? ""} />
  <br />
{/snippet}

{#snippet correctAnswer()}
  <b class="text-xl">{t("feedback.possible-correct-solution")}:</b>
  <br />
  <Markdown md={questionState.feedbackObject?.correctAnswer ?? ""} />
{/snippet}

<svelte:window on:keydown={onKeyDown} />
