// front-end/src/components/DrawPseudoCode.tsx
import { useState, type ReactElement } from "react"
import { IoColorPaletteOutline } from "react-icons/io5"
import { MdContentCopy } from "react-icons/md"
import { TbListNumbers } from "react-icons/tb"
import type { PseudoCode } from "@shared/utils/pseudoCodeUtils.ts"
import { Markdown } from "@/components/Markdown.tsx"
import { Toggle } from "@/components/ui/toggle.tsx"
import { Tooltip, TooltipContent, TooltipTrigger } from "@/components/ui/tooltip"
import { useTranslation } from "@/hooks/useTranslation"
import { pseudoCodeToString } from "@/utils/renderPseudoCode.ts"

/*
Could use this for coloring the pseudocode
https://www.w3schools.com/tags/ref_colornames.asp
*/
export const keyWordsColor = "DodgerBlue"
export const functionColor = "DarkCyan"
export const variableColor = "IndianRed"
export const controlFlowColor = "SeaGreen"
export const printStatementColor = "Orange"

export function DrawPseudoCode({ displayCode }: { displayCode: string }): ReactElement {
  const pseudoCodeStringParse: PseudoCode = JSON.parse(displayCode) as PseudoCode

  const { pseudoCodeString, pseudoCodeStringColor, pseudoCodeStringLatex } =
    pseudoCodeToString(pseudoCodeStringParse)

  const { t } = useTranslation()

  const numCodeLines = pseudoCodeString.length

  const [toggleStateLines, setToggleStateLines] = useState(true)
  const [toggleStateColor, setToggleStateColor] = useState(true)
  const [recentlyCopied, setRecentlyCopied] = useState(false)

  const handleClickCopyIcon: () => void = () => {
    void navigator.clipboard
      .writeText(pseudoCodeStringLatex.filter((codeLine) => codeLine.trim() !== "").join("\n"))
      .then(() => setRecentlyCopied(true))
  }

  return (
    <div className="my-5">
      <div className="relative">
        <div className="min-h-28 overflow-hidden rounded-lg border border-gray-300 bg-gray-50 dark:border-gray-700 dark:bg-gray-800">
          <div className="whitespace-nowrap">
            {toggleStateColor ? (
              <pre className="overflow-x-auto whitespace-pre py-3 pl-5 pr-10 font-mono leading-normal text-gray-900 dark:text-gray-100">
                <CodeJSX
                  currentCode={pseudoCodeStringColor}
                  toggleStateLines={toggleStateLines}
                  numCodeLines={numCodeLines}
                />
              </pre>
            ) : (
              <pre className="overflow-x-auto whitespace-pre py-3 pl-5 pr-10 font-mono leading-normal text-gray-900 dark:text-gray-100">
                <CodeJSX
                  currentCode={pseudoCodeString}
                  toggleStateLines={toggleStateLines}
                  numCodeLines={numCodeLines}
                />
              </pre>
            )}
          </div>
        </div>
        <div className="absolute right-1 top-1 flex flex-col items-center space-y-1 rounded-lg dark:border-gray-700 dark:bg-gray-800">
          <Tooltip placement={`right`}>
            <TooltipTrigger asChild>
              <div>
                <Toggle
                  size="sm"
                  pressed={toggleStateLines}
                  onPressedChange={() => setToggleStateLines(!toggleStateLines)}
                >
                  <TbListNumbers />
                </Toggle>
              </div>
            </TooltipTrigger>
            <TooltipContent>{t("lineNumberTooltip")}</TooltipContent>
          </Tooltip>
          <Tooltip placement={`right`}>
            <TooltipTrigger asChild>
              <div>
                <Toggle
                  size="sm"
                  pressed={toggleStateColor}
                  onPressedChange={() => setToggleStateColor(!toggleStateColor)}
                >
                  <IoColorPaletteOutline />
                </Toggle>
              </div>
            </TooltipTrigger>
            <TooltipContent>{t("colorHighlightingTooltip")}</TooltipContent>
          </Tooltip>
          <Tooltip placement={`right`}>
            <TooltipTrigger asChild>
              <div
                onClick={handleClickCopyIcon}
                onMouseLeave={() => {
                  setTimeout(() => setRecentlyCopied(false), 200)
                }}
                className={`inline-flex h-8 items-center justify-center rounded-md px-2.5 text-sm font-medium ring-offset-background transition-colors hover:bg-muted hover:text-muted-foreground focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring focus-visible:ring-offset-2 disabled:pointer-events-none disabled:opacity-50 data-[state=on]:bg-accent data-[state=on]:text-accent-foreground`}
              >
                <MdContentCopy className="h-4 w-4" />
              </div>
            </TooltipTrigger>
            <TooltipContent>{recentlyCopied ? t("copyLinkCopied") : t("copyCodeLatex")}</TooltipContent>
          </Tooltip>
        </div>
      </div>
    </div>
  )
}

const CodeJSX = ({
  currentCode,
  toggleStateLines,
  numCodeLines,
}: {
  currentCode: string[]
  toggleStateLines: boolean
  numCodeLines: number
}) => {
  return (
    <>
      {currentCode.map((cd, index) => (
        <div key={index}>
          <span
            className={`text-right ${numCodeLines > 9 ? "min-w-8" : "min-w-6"} inline-block pr-1 ${toggleStateLines ? "text-gray-400 dark:text-gray-600" : "text-transparent"} no-select`}
          >
            {index + 1}:
          </span>
          <Markdown md={`${" ".repeat(getAmountLeadingWhiteSpaces(cd))}$${addBiggerLineSpacing(cd)}$`} />
        </div>
      ))}
    </>
  )
}

/**
 * Adds 0.15em to each line
 *
 * Otherwise the lines are too close to each other
 * For example:
 * 1: \\frac{m}{5}
 * 2: \\frac{m}{5}
 * Those nearly touch
 *
 * @param code
 */
function addBiggerLineSpacing(code: string): string {
  return `${code} \\\\[0.15em]`
}

function getAmountLeadingWhiteSpaces(text: string): number {
  let count = 0
  for (let i = 0; i < text.length; i++) {
    if (text[i] === " ") {
      count++
    } else {
      break
    }
  }
  return count
}

// packages/svelte-front-end/src/lib/components/PseudoCode/DrawPseudoCode.svelte
<script lang="ts">
  import { browser } from "$app/environment"
  import CodeComp from "$lib/components/PseudoCode/CodeComp.svelte"
  import { pseudoCodeToString } from "$lib/components/PseudoCode/renderPseudoCode.ts"
  import { toggleVariants } from "$lib/components/ui/toggle"
  import { globalTranslations } from "$lib/translation.ts"
  import { cn } from "$lib/utils.ts"
  import { getLanguage } from "$lib/utils/langState.svelte.ts"
  import { Toggle, Tooltip } from "bits-ui"
  import { Copy, ListOrdered, Palette } from "lucide-svelte"
  import type { PseudoCode } from "@shared/utils/pseudoCodeUtils.ts"
  import { tFunction } from "@shared/utils/translations.ts"

  interface Props {
    displayCode: string
  }
  const { displayCode }: Props = $props()

  const pseudoCodeStringParse: PseudoCode = JSON.parse(displayCode) as PseudoCode

  const { pseudoCodeString, pseudoCodeStringColor, pseudoCodeStringLatex } =
    pseudoCodeToString(pseudoCodeStringParse)

  const lang = $derived(getLanguage())
  const { t } = $derived(tFunction(globalTranslations, lang))

  const numCodeLines = pseudoCodeString.length

  let toggleStateLines = $state(true)
  let toggleStateColor = $state(true)
  let recentlyCopied = $state(false)

  const handleClickCopyIcon: () => void = () => {
    if (!browser) return
    void navigator.clipboard
      .writeText(pseudoCodeStringLatex.filter((codeLine) => codeLine.trim() !== "").join("\n"))
      .then(() => {
        recentlyCopied = true
      })
  }
</script>

<div class="my-5">
  <div class="relative">
    <div
      class="min-h-32 overflow-hidden rounded-lg border border-gray-300 bg-gray-50 dark:border-gray-700 dark:bg-gray-800"
    >
      <div class="whitespace-nowrap">
        {#if toggleStateColor}
          <pre
            class="pt-font-mono -mt-2 -mb-4 overflow-x-auto pr-10 pl-5 leading-normal whitespace-pre text-gray-900 dark:text-gray-100">
            <CodeComp currentCode={pseudoCodeStringColor} {toggleStateLines} {numCodeLines} />
          </pre>
        {:else}
          <pre
            class="-mt-2 -mb-4 overflow-x-auto pr-10 pl-5 font-mono leading-normal whitespace-pre text-gray-900 dark:text-gray-100">
            <CodeComp currentCode={pseudoCodeString} {toggleStateLines} {numCodeLines} />
          </pre>
        {/if}
      </div>
    </div>
    <div
      class="absolute top-1 right-1 flex flex-col items-center space-y-1 rounded-lg dark:border-gray-700 dark:bg-gray-800"
    >
      <Tooltip.Provider>
        <Tooltip.Root>
          <Tooltip.Trigger>
            <Toggle.Root
              pressed={toggleStateLines}
              onPressedChange={() => {
                toggleStateLines = !toggleStateLines
              }}
              class={cn(
                toggleVariants["base"],
                toggleVariants["variants"]["variant"]["default"],
                toggleVariants["variants"]["size"]["sm"],
                "hover:cursor-pointer",
              )}
            >
              <ListOrdered />
            </Toggle.Root>
          </Tooltip.Trigger>
          <Tooltip.Content>
            {t("lineNumberTooltip")}
          </Tooltip.Content>
        </Tooltip.Root>
      </Tooltip.Provider>
      <Tooltip.Provider>
        <Tooltip.Root>
          <Tooltip.Trigger>
            <Toggle.Root
              pressed={toggleStateColor}
              onPressedChange={() => {
                toggleStateColor = !toggleStateColor
              }}
              class={cn(
                toggleVariants["base"],
                toggleVariants["variants"]["variant"]["default"],
                toggleVariants["variants"]["size"]["sm"],
                "hover:cursor-pointer",
              )}
            >
              <Palette />
            </Toggle.Root>
          </Tooltip.Trigger>
          <Tooltip.Content>
            {t("colorHighlightingTooltip")}
          </Tooltip.Content>
        </Tooltip.Root>
      </Tooltip.Provider>
      <Tooltip.Provider>
        <Tooltip.Root>
          <Tooltip.Trigger>
            <div
              role="button"
              tabindex="0"
              onclick={handleClickCopyIcon}
              onkeydown={(e) => (e.key === "Enter" || e.key === " ") && handleClickCopyIcon()}
              onmouseleave={() => {
                setTimeout(() => {
                  recentlyCopied = false
                }, 500)
              }}
              class="ring-offset-background hover:bg-muted hover:text-muted-foreground focus-visible:ring-ring data-[state=on]:bg-accent data-[state=on]:text-accent-foreground inline-flex h-8 items-center justify-center rounded-md px-2.5 text-sm font-medium transition-colors focus-visible:ring-2 focus-visible:ring-offset-2 focus-visible:outline-none disabled:pointer-events-none disabled:opacity-50"
            >
              <Copy class="h-4 w-4" />
            </div>
          </Tooltip.Trigger>
          <Tooltip.Content>
            {recentlyCopied ? t("copyLinkCopied") : t("copyCodeLatex")}
          </Tooltip.Content>
        </Tooltip.Root>
      </Tooltip.Provider>
    </div>
  </div>
</div>
